Repository Yuanrui-Mdt-Info/airbyte, pull requests merged in 2022-11, with the labels that each got.

#28 CU-3640u3v_FE-implement-UI-for-the-sign-up-flow_Muhammad-Akif
  airbyte-webapp/.env
  airbyte-webapp/.gitignore
  airbyte-webapp/public/SignupCover.png
  airbyte-webapp/public/daspireList1.svg
  airbyte-webapp/public/daspireList2.svg
  airbyte-webapp/public/daspireList3.svg
  airbyte-webapp/public/daspireList4.svg
  airbyte-webapp/public/daspireList5.svg
  airbyte-webapp/public/daspireList6.svg
  airbyte-webapp/public/daspireWhiteLogo.svg
  airbyte-webapp/src/components/base/Button/LoadingButton.tsx
  airbyte-webapp/src/components/base/Button/types.tsx
  airbyte-webapp/src/core/request/AirbyteRequestService.ts
  airbyte-webapp/src/hooks/services/Onboarding/OnboardingService.tsx
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.module.scss
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/LoginPage/index.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.module.scss
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.module.scss
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/index.tsx
  airbyte-webapp/src/pages/AuthPage/components/FormComponents.tsx
  airbyte-webapp/src/pages/routePaths.tsx
  airbyte-webapp/src/pages/routes.tsx
  airbyte-webapp/src/services/auth/AuthService.ts
  airbyte-webapp/src/services/auth/AuthSpecificationService.tsx
Labels: area/platform, team/frontend

#29 CU-3qebrhw_QA-Sign-up-flow-testing_Abi---
  airbyte-api/src/main/openapi/config.yaml
  airbyte-server/src/main/java/io/airbyte/server/handlers/WorkspacesHandler.java
  airbyte-webapp/.env
  airbyte-webapp/.gitignore
  airbyte-webapp/public/SignupCover.png
  airbyte-webapp/public/daspireDashboard.png
  airbyte-webapp/public/daspireList1.svg
  airbyte-webapp/public/daspireList2.svg
  airbyte-webapp/public/daspireList3.svg
  airbyte-webapp/public/daspireList4.svg
  airbyte-webapp/public/daspireList5.svg
  airbyte-webapp/public/daspireList6.svg
  airbyte-webapp/public/daspireLogo.svg
  airbyte-webapp/public/daspireLogo1.svg
  airbyte-webapp/public/daspireWhiteLogo.svg
  airbyte-webapp/src/components/CenteredPageComponents/BigButton.tsx
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/components/ConnectionSettingsCell.tsx
  airbyte-webapp/src/components/EntityTable/components/SwitchButton.tsx
  airbyte-webapp/src/components/PageTitle/PageTitle.tsx
  airbyte-webapp/src/components/Table/Table.tsx
  airbyte-webapp/src/components/base/Button/Button.tsx
  airbyte-webapp/src/components/base/Button/LoadingButton.tsx
  airbyte-webapp/src/components/base/Button/types.tsx
  airbyte-webapp/src/core/request/AirbyteRequestService.ts
  airbyte-webapp/src/hooks/services/Onboarding/OnboardingService.tsx
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.module.scss
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/LoginPage/index.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.module.scss
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.module.scss
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/index.tsx
  airbyte-webapp/src/pages/AuthPage/components/FormComponents.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/ConnectionsTable.tsx
  airbyte-webapp/src/pages/OnboardingPage/OnboardingPage.tsx
  airbyte-webapp/src/pages/OnboardingPage/components/TitlesBlock.tsx
  airbyte-webapp/src/pages/OnboardingPage/components/WelcomeStep.tsx
  airbyte-webapp/src/pages/routePaths.tsx
  airbyte-webapp/src/pages/routes.tsx
  airbyte-webapp/src/services/auth/AuthService.ts
  airbyte-webapp/src/services/auth/AuthSpecificationService.tsx
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
  airbyte-webapp/src/views/layout/SideBar/SideBar.module.scss
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend, area/api, area/server

#30 CU-37bxh8m_FE-integration-with-BE-for-add-connection-functionalities_Muhammad-Akif
  airbyte-webapp/.gitignore
  airbyte-webapp/public/favicon.ico
  airbyte-webapp/public/favicon1.ico
  airbyte-webapp/public/index.html
  airbyte-webapp/src/components/Alert/Alert.tsx
  airbyte-webapp/src/components/Alert/index.tsx
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/components/SwitchButton.tsx
  airbyte-webapp/src/components/HeadTitle/HeadTitle.tsx
  airbyte-webapp/src/components/base/Button/Button.tsx
  airbyte-webapp/src/core/request/AirbyteClient.ts
  airbyte-webapp/src/core/request/AirbyteRequestService.ts
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/ConnectionsTable.tsx
  airbyte-webapp/src/pages/OnboardingPage/OnboardingPage.tsx
  airbyte-webapp/src/pages/routes.tsx
  airbyte-webapp/src/services/auth/AuthService.ts
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#31 CU-37bxh8m_FE-integration-with-BE-for-add-connection-functionalities_Muhammad-Akif
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/components/SwitchButton.tsx
  airbyte-webapp/src/config/defaultConfig.ts
  airbyte-webapp/src/core/request/AirbyteClient.ts
  airbyte-webapp/src/core/request/apiOverride.ts
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/ConnectionsTable.tsx
  airbyte-webapp/src/pages/OnboardingPage/components/WelcomeStep.tsx
  airbyte-webapp/src/pages/routes.tsx
Labels: area/platform, team/frontend

#32 CU-376af42_QA-add-a-connection-flow_Abi---
  airbyte-webapp/.gitignore
  airbyte-webapp/public/favicon.ico
  airbyte-webapp/public/favicon1.ico
  airbyte-webapp/public/index.html
  airbyte-webapp/src/components/Alert/Alert.tsx
  airbyte-webapp/src/components/Alert/index.tsx
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/components/SwitchButton.tsx
  airbyte-webapp/src/components/HeadTitle/HeadTitle.tsx
  airbyte-webapp/src/components/base/Button/Button.tsx
  airbyte-webapp/src/config/defaultConfig.ts
  airbyte-webapp/src/core/request/AirbyteClient.ts
  airbyte-webapp/src/core/request/AirbyteRequestService.ts
  airbyte-webapp/src/core/request/apiOverride.ts
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/ConnectionsTable.tsx
  airbyte-webapp/src/pages/OnboardingPage/OnboardingPage.tsx
  airbyte-webapp/src/pages/OnboardingPage/components/WelcomeStep.tsx
  airbyte-webapp/src/pages/routes.tsx
  airbyte-webapp/src/services/auth/AuthService.ts
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#33 CU-37bxrt6_FE-upgrade-plan-UI_Muhammad-Akif
  airbyte-webapp/.env
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/core/request/AirbyteRequestService.ts
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/ConnectionsTable.tsx
  airbyte-webapp/src/services/auth/AuthSpecificationService.tsx
  airbyte-webapp/src/views/layout/SideBar/SideBar.module.scss
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#34 CU-37bxrt6_FE-upgrade-plan-UI_Muhammad-Akif
  airbyte-webapp/src/config/configProviders.ts
  airbyte-webapp/src/config/defaultConfig.ts
  airbyte-webapp/src/core/request/AirbyteRequestService.ts
  airbyte-webapp/src/core/request/apiOverride.ts
Labels: area/platform, team/frontend

#35 CU-37bxrt6_FE-upgrade-plan-UI_Muhammad-Akif
  airbyte-webapp/src/config/configProviders.ts
  airbyte-webapp/src/core/request/AirbyteRequestService.ts
  airbyte-webapp/src/core/request/apiOverride.ts
  airbyte-webapp/src/services/connector/DestinationDefinitionService.ts
  airbyte-webapp/src/services/connector/DestinationDefinitionSpecificationService.tsx
  airbyte-webapp/src/services/connector/SourceDefinitionService.ts
  airbyte-webapp/src/services/connector/SourceDefinitionSpecificationService.tsx
  airbyte-webapp/src/services/job/JobService.tsx
  airbyte-webapp/src/services/logs/LogsService.tsx
  airbyte-webapp/src/services/workspaces/WorkspacesService.tsx
Labels: area/platform, team/frontend

#36 CU-37bzx07_Ability-to-enabledisable-a-connection_haimin-
  airbyte-webapp/.env
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/config/configProviders.ts
  airbyte-webapp/src/config/defaultConfig.ts
  airbyte-webapp/src/core/request/AirbyteRequestService.ts
  airbyte-webapp/src/core/request/apiOverride.ts
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/ConnectionsTable.tsx
  airbyte-webapp/src/services/auth/AuthSpecificationService.tsx
  airbyte-webapp/src/services/connector/DestinationDefinitionService.ts
  airbyte-webapp/src/services/connector/DestinationDefinitionSpecificationService.tsx
  airbyte-webapp/src/services/connector/SourceDefinitionService.ts
  airbyte-webapp/src/services/connector/SourceDefinitionSpecificationService.tsx
  airbyte-webapp/src/services/job/JobService.tsx
  airbyte-webapp/src/services/logs/LogsService.tsx
  airbyte-webapp/src/services/workspaces/WorkspacesService.tsx
  airbyte-webapp/src/views/layout/SideBar/SideBar.module.scss
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#37 CU-37bxrt6_FE-upgrade-plan-UI_Muhammad-Akif
  airbyte-webapp/src/components/MainPageWithScroll/MainPageWithScroll.module.scss
  airbyte-webapp/src/config/configProviders.ts
  airbyte-webapp/src/core/ApiServices.tsx
  airbyte-webapp/src/core/request/AirbyteRequestService.ts
  airbyte-webapp/src/core/request/apiOverride.ts
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/hooks/services/useConnector.tsx
  airbyte-webapp/src/hooks/services/useConnectorAuth.tsx
  airbyte-webapp/src/hooks/services/useDestinationHook.tsx
  airbyte-webapp/src/hooks/services/useSourceHook.tsx
  airbyte-webapp/src/hooks/services/useWorkspace.tsx
  airbyte-webapp/src/services/workspaces/WorkspacesService.tsx
Labels: area/platform, team/frontend

#38 CU-37bxrt6_FE-upgrade-plan-UI_Muhammad-Akif
  airbyte-webapp/public/daspireLogo1.svg
  airbyte-webapp/src/components/EmptyResourceListView/EmptyResourceListView.tsx
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/utils.tsx
  airbyte-webapp/src/components/MainPageWithScroll/MainPageWithScroll.module.scss
  airbyte-webapp/src/components/base/Button/Button.tsx
  airbyte-webapp/src/components/base/Button/types.tsx
  airbyte-webapp/src/config/links.ts
  airbyte-webapp/src/core/domain/connector/DestinationDefinitionService.ts
  airbyte-webapp/src/core/domain/connector/SourceDefinitionService.ts
  airbyte-webapp/src/hooks/services/useDocumentation.ts
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/ConnectionsTable.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UnauthorizedModal.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/scss/_colors.scss
  airbyte-webapp/src/scss/export.module.scss
  airbyte-webapp/src/services/connector/DestinationDefinitionService.ts
  airbyte-webapp/src/services/connector/SourceDefinitionService.ts
  airbyte-webapp/src/theme.ts
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#40 CU-3t9231b_bugLast-sync-at-should-be-a-time-not-the-status_Abi---
  airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/source.py
  airbyte-integrations/connectors/source-amazon-seller-partner/unit_tests/test_finance_streams.py
  airbyte-integrations/connectors/source-amazon-seller-partner/unit_tests/test_reports_streams_rate_limits.py
  airbyte-integrations/connectors/source-amazon-seller-partner/unit_tests/test_reports_streams_settlement_report.py
  airbyte-integrations/connectors/source-amazon-seller-partner/unit_tests/test_source.py
  airbyte-integrations/connectors/source-amazon-seller-partner/unit_tests/test_transform_function.py
  airbyte-webapp/build.gradle
  airbyte-webapp/public/daspireLogo1.svg
  airbyte-webapp/src/components/EmptyResourceListView/EmptyResourceListView.tsx
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/utils.tsx
  airbyte-webapp/src/components/base/Button/Button.tsx
  airbyte-webapp/src/components/base/Button/types.tsx
  airbyte-webapp/src/config/configProviders.ts
  airbyte-webapp/src/config/links.ts
  airbyte-webapp/src/core/ApiServices.tsx
  airbyte-webapp/src/core/domain/connector/DestinationDefinitionService.ts
  airbyte-webapp/src/core/domain/connector/SourceDefinitionService.ts
  airbyte-webapp/src/core/request/AirbyteRequestService.ts
  airbyte-webapp/src/core/request/apiOverride.ts
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/hooks/services/useConnector.tsx
  airbyte-webapp/src/hooks/services/useConnectorAuth.tsx
  airbyte-webapp/src/hooks/services/useDestinationHook.tsx
  airbyte-webapp/src/hooks/services/useDocumentation.ts
  airbyte-webapp/src/hooks/services/useSourceHook.tsx
  airbyte-webapp/src/hooks/services/useWorkspace.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/ConnectionsTable.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UnauthorizedModal.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/scss/_colors.scss
  airbyte-webapp/src/scss/export.module.scss
  airbyte-webapp/src/services/connector/DestinationDefinitionService.ts
  airbyte-webapp/src/services/connector/SourceDefinitionService.ts
  airbyte-webapp/src/services/workspaces/WorkspacesService.tsx
  airbyte-webapp/src/theme.ts
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
  docs/setup-guide/destinations/bigquery.md
  docs/setup-guide/destinations/clickhouse.md
  docs/setup-guide/destinations/mysql.md
  docs/setup-guide/destinations/postgres.md
  docs/setup-guide/destinations/redshift.md
  docs/setup-guide/destinations/snowflake.md
  docs/setup-guide/sources/amazon-ads.md
  docs/setup-guide/sources/amazon-seller-partner.md
  docs/setup-guide/sources/bigcommerce.md
  docs/setup-guide/sources/magento.md
  docs/setup-guide/sources/mysql.md
  docs/setup-guide/sources/netsuite.md
  docs/setup-guide/sources/shopify.md
  docs/setup-guide/sources/woocommerce.md
Labels: area/connectors, area/platform, team/frontend, area/documentation

#42 CU-37bxrt6_FE-upgrade-plan-UI_Muhammad-Akif
  airbyte-webapp/src/components/EmptyResourceListView/EmptyResourceListView.tsx
  airbyte-webapp/src/components/EntityTable/components/LastSyncCell.tsx
  airbyte-webapp/src/components/TabMenu/TabMenu.tsx
  airbyte-webapp/src/components/TabMenu/components/TabItem.tsx
  airbyte-webapp/src/components/TabMenu/index.tsx
  airbyte-webapp/src/components/icons/CalendarIcon.tsx
  airbyte-webapp/src/components/icons/RightArrowHeadIcon.tsx
  airbyte-webapp/src/components/icons/TickIcon.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/components/PaymentNav.tsx
  airbyte-webapp/src/pages/PaymentPage/index.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/BillingAndPaymentPage/BillingAndPaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/BillingAndPaymentPage/index.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/SelectPlanPage.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/index.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/AccountSettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/index.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/components/PlanClause.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/index.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/style.module.scss
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/index.tsx
  airbyte-webapp/src/pages/routePaths.tsx
  airbyte-webapp/src/pages/routes.tsx
  airbyte-webapp/src/views/common/ErrorOccurredView/ErrorOccurredView.module.scss
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#43 CU-3t9231b_bugLast-sync-at-should-be-a-time-not-the-status_Abi---
  airbyte-webapp/src/components/EmptyResourceListView/EmptyResourceListView.tsx
  airbyte-webapp/src/components/EntityTable/components/LastSyncCell.tsx
  airbyte-webapp/src/components/TabMenu/TabMenu.tsx
  airbyte-webapp/src/components/TabMenu/components/TabItem.tsx
  airbyte-webapp/src/components/TabMenu/index.tsx
  airbyte-webapp/src/components/icons/CalendarIcon.tsx
  airbyte-webapp/src/components/icons/RightArrowHeadIcon.tsx
  airbyte-webapp/src/components/icons/TickIcon.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/components/PaymentNav.tsx
  airbyte-webapp/src/pages/PaymentPage/index.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/BillingAndPaymentPage/BillingAndPaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/BillingAndPaymentPage/index.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/SelectPlanPage.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/index.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/AccountSettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/index.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/components/PlanClause.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/index.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/style.module.scss
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/index.tsx
  airbyte-webapp/src/pages/routePaths.tsx
  airbyte-webapp/src/pages/routes.tsx
  airbyte-webapp/src/views/common/ErrorOccurredView/ErrorOccurredView.module.scss
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#44 CU-37bxrt6_FE-upgrade-plan-UI_Muhammad-Akif
  airbyte-webapp/src/components/MainPageWithScroll/MainPageWithScroll.module.scss
  airbyte-webapp/src/components/base/Card/Card.module.scss
  airbyte-webapp/src/config/configProviders.ts
  airbyte-webapp/src/core/functions/numberFormatter.ts
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.module.scss
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/SelectPlanPage.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/components/Slider.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/components/SliderMark.tsx
  airbyte-webapp/src/scss/_variables.scss
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#45 CU-37bxrt6_FE-upgrade-plan-UI_Muhammad-Akif
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/base/DropDown/components/DropdownIndicator.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/CreationFormPage.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/SelectPlanPage.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/components/Slider.tsx
  airbyte-webapp/src/pages/routes.tsx
  airbyte-webapp/src/services/workspaces/WorkspacesService.tsx
  airbyte-webapp/src/views/Connection/CatalogTree/components/SyncSettingsDropdown.tsx
  airbyte-webapp/src/views/Connection/CatalogTree/styles.tsx
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#46 CU-3c6jz0w_Rename-Source-Name-to-Store-Name_Jerry-Lee---
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.yaml
  airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/spec.py
Labels: area/connectors

#47 CU-3c6jz0w_Rename-Source-Name-to-Store-Name_Abi---
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.yaml
  airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/spec.py
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/MainPageWithScroll/MainPageWithScroll.module.scss
  airbyte-webapp/src/components/base/Card/Card.module.scss
  airbyte-webapp/src/components/base/DropDown/components/DropdownIndicator.tsx
  airbyte-webapp/src/config/configProviders.ts
  airbyte-webapp/src/core/functions/numberFormatter.ts
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/CreationFormPage.tsx
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.module.scss
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/SelectPlanPage.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/components/Slider.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/components/SliderMark.tsx
  airbyte-webapp/src/pages/routes.tsx
  airbyte-webapp/src/scss/_variables.scss
  airbyte-webapp/src/services/workspaces/WorkspacesService.tsx
  airbyte-webapp/src/views/Connection/CatalogTree/components/SyncSettingsDropdown.tsx
  airbyte-webapp/src/views/Connection/CatalogTree/styles.tsx
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/connectors, area/platform, team/frontend

#48 CU-3dmfq0y_Issue-for-source-amazon-ads-and-source-amazon-seller-partner-dont-show-the-store-name-when-the-system-is-running_Jerry-Lee---
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.yaml
Labels: area/connectors

#49 CU-3dmfq0y_Issue-for-source-amazon-ads-and-source-amazon-seller-partner-dont-show-the-store-name-when-the-system-is-running_Abi---
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.yaml
Labels: area/connectors

#50 CU-37bxrt6_FE-billing--payment-UI_Muhammad-Akif
  airbyte-webapp/src/App.tsx
  airbyte-webapp/src/core/ApiServices.tsx
  airbyte-webapp/src/core/AuthContext/AuthContext.tsx
  airbyte-webapp/src/core/AuthContext/index.tsx
  airbyte-webapp/src/core/request/AirbyteRequestService.ts
  airbyte-webapp/src/core/request/apiOverride.ts
  airbyte-webapp/src/hooks/services/Onboarding/OnboardingService.tsx
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/hooks/services/useConnector.tsx
  airbyte-webapp/src/hooks/services/useConnectorAuth.tsx
  airbyte-webapp/src/hooks/services/useDestinationHook.tsx
  airbyte-webapp/src/hooks/services/useSourceHook.tsx
  airbyte-webapp/src/hooks/services/useWorkspace.tsx
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/routes.tsx
  airbyte-webapp/src/services/auth/AuthService.ts
  airbyte-webapp/src/services/connector/DestinationDefinitionService.ts
  airbyte-webapp/src/services/connector/DestinationDefinitionSpecificationService.tsx
  airbyte-webapp/src/services/connector/SourceDefinitionService.ts
  airbyte-webapp/src/services/connector/SourceDefinitionSpecificationService.tsx
  airbyte-webapp/src/services/job/JobService.tsx
  airbyte-webapp/src/services/logs/LogsService.tsx
  airbyte-webapp/src/services/workspaces/WorkspacesService.tsx
Labels: area/platform, team/frontend

#51 CU-3t9231b_bugLast-sync-at-should-be-a-time-not-the-status_Abi---
  airbyte-webapp/src/App.tsx
  airbyte-webapp/src/core/ApiServices.tsx
  airbyte-webapp/src/core/AuthContext/AuthContext.tsx
  airbyte-webapp/src/core/AuthContext/index.tsx
  airbyte-webapp/src/core/request/AirbyteRequestService.ts
  airbyte-webapp/src/core/request/apiOverride.ts
  airbyte-webapp/src/hooks/services/Onboarding/OnboardingService.tsx
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/hooks/services/useConnector.tsx
  airbyte-webapp/src/hooks/services/useConnectorAuth.tsx
  airbyte-webapp/src/hooks/services/useDestinationHook.tsx
  airbyte-webapp/src/hooks/services/useSourceHook.tsx
  airbyte-webapp/src/hooks/services/useWorkspace.tsx
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/routes.tsx
  airbyte-webapp/src/services/auth/AuthService.ts
  airbyte-webapp/src/services/connector/DestinationDefinitionService.ts
  airbyte-webapp/src/services/connector/DestinationDefinitionSpecificationService.tsx
  airbyte-webapp/src/services/connector/SourceDefinitionService.ts
  airbyte-webapp/src/services/connector/SourceDefinitionSpecificationService.tsx
  airbyte-webapp/src/services/job/JobService.tsx
  airbyte-webapp/src/services/logs/LogsService.tsx
  airbyte-webapp/src/services/workspaces/WorkspacesService.tsx
Labels: area/platform, team/frontend

#52 CU-3wmftg4_issue-could-not-get-the-documentation-of-amazon-ads-and-amazon-seller-partner_Jerry-Lee---
  airbyte-config/init/src/main/resources/seed/destination_definitions.yaml
  airbyte-config/init/src/main/resources/seed/source_definitions.yaml
  airbyte-integrations/bases/base-java/src/main/java/io/airbyte/integrations/base/JavaBaseConstants.java
  airbyte-integrations/bases/base-java/src/main/java/io/airbyte/integrations/destination/StandardNameTransformer.java
  airbyte-integrations/bases/base-normalization/normalization/transform_catalog/catalog_processor.py
  airbyte-integrations/connectors/destination-mysql/src/test/java/io/airbyte/integrations/destination/mysql/MySQLNameTransformerTest.java
Labels: area/connectors, normalization
