Repository Yuanrui-Mdt-Info/airbyte, pull requests merged in 2022-12, with the labels that each got.

#53 CU-3dmghyy_bugAfter-filling-in-some-content-casually-click-Set-source-and-the-failure-and-success-prompts-will-pop-up-below_Abi---
  airbyte-config/init/src/main/resources/seed/destination_definitions.yaml
  airbyte-config/init/src/main/resources/seed/source_definitions.yaml
  airbyte-integrations/bases/base-java/src/main/java/io/airbyte/integrations/base/JavaBaseConstants.java
  airbyte-integrations/bases/base-java/src/main/java/io/airbyte/integrations/destination/StandardNameTransformer.java
  airbyte-integrations/bases/base-normalization/normalization/transform_catalog/catalog_processor.py
  airbyte-integrations/connectors/destination-mysql/src/test/java/io/airbyte/integrations/destination/mysql/MySQLNameTransformerTest.java
Labels: area/connectors, normalization

#54 CU-37bxrt6_FE-billing--payment-UI_Muhammad-Akif
  airbyte-webapp/src/components/ArrayOfObjectsEditor/ArrayOfObjectsEditor.tsx
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/JobItem/JobItem.tsx
  airbyte-webapp/src/config/configProviders.ts
  airbyte-webapp/src/core/request/AirbyteClient.ts
  airbyte-webapp/src/locales/en.json
Labels: area/platform, team/frontend

#55 CU-3dzynxy_bugNo-response-to-click-switch_Abi---
  airbyte-webapp/src/components/ArrayOfObjectsEditor/ArrayOfObjectsEditor.tsx
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/JobItem/JobItem.tsx
  airbyte-webapp/src/config/configProviders.ts
  airbyte-webapp/src/core/request/AirbyteClient.ts
  airbyte-webapp/src/locales/en.json
Labels: area/platform, team/frontend

#58 CU-3e5x3pu_bugWhen-the-token-expires-the-re-login-page-prompts-that-there-is-no-access-permission_Muhammad-Akif
  airbyte-webapp/package-lock.json
  airbyte-webapp/package.json
  airbyte-webapp/src/App.tsx
  airbyte-webapp/src/components/ArrayOfObjectsEditor/ArrayOfObjectsEditor.tsx
  airbyte-webapp/src/components/LabeledInput/LabeledInput.tsx
  airbyte-webapp/src/components/MainPageWithScroll/MainPageWithScroll.module.scss
  airbyte-webapp/src/components/MainPageWithScroll/MainPageWithScroll.tsx
  airbyte-webapp/src/components/Separator/Separator.tsx
  airbyte-webapp/src/components/Separator/index.tsx
  airbyte-webapp/src/components/SimpleTableComponents/SimpleTableComponents.tsx
  airbyte-webapp/src/components/base/Input/Input.module.scss
  airbyte-webapp/src/components/base/Input/Input.tsx
  airbyte-webapp/src/components/icons/DashIcon.tsx
  airbyte-webapp/src/core/AuthContext/AuthContext.tsx
  airbyte-webapp/src/core/request/AirbyteClient.ts
  airbyte-webapp/src/hooks/useStateCallback.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/packages/cloud/views/credits/CreditsPage/CreditsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UnauthorizedModal.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/ConnectionItemPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.module.scss
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/BillingAndPaymentPage/BillingAndPaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/BillingAndPaymentPage/components/PaymentForm.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/BillingAndPaymentPage/components/PlanCard.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/BillingAndPaymentPage/components/StripeElements.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/SelectPlanPage.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/components/EnterpriseCell.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/components/FeaturesCard.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/components/ProcessionalCell.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/components/Range.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/components/RangeCard.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/components/RangeMark.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/components/CancelPlanModal.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#60 CU-3xbcnkr_Show-un-hide-Snowflake-destination_Jerry-Lee---
  airbyte-config/init/src/main/resources/seed/destination_definitions.yaml
  airbyte-config/init/src/main/resources/seed/destination_specs.yaml
  airbyte-integrations/connectors/destination-snowflake/src/main/resources/spec.json
Labels: area/connectors

#61 CU-3xbcnkr_Show-un-hide-Snowflake-destination_haimin-
  airbyte-config/init/src/main/resources/seed/destination_definitions.yaml
  airbyte-config/init/src/main/resources/seed/destination_specs.yaml
  airbyte-integrations/connectors/destination-snowflake/src/main/resources/spec.json
Labels: area/connectors

#62 CU-37bxrt6_FE-billing--payment-UI_Muhammad-Akif
  airbyte-webapp/src/core/AuthContext/AuthContext.tsx
  airbyte-webapp/src/core/AuthContext/authenticatedUser.ts
  airbyte-webapp/src/pages/routes.tsx
Labels: area/platform, team/frontend

#63 CU-3e5x3pu_bugWhen-the-token-expires-the-re-login-page-prompts-that-there-is-no-access-permission_Abi---
  airbyte-webapp/src/core/AuthContext/AuthContext.tsx
  airbyte-webapp/src/core/AuthContext/authenticatedUser.ts
  airbyte-webapp/src/pages/routes.tsx
Labels: area/platform, team/frontend

#66 CU-3eppa1c_Link-privacy-and-terms-page-to-webapp_Anet-
  airbyte-webapp/src/config/links.ts
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
Labels: area/platform, team/frontend

#67 CU-3wu2p39_Count-usage---no-of-rows_Roy--
  .env
  airbyte-api/src/main/openapi/config.yaml
  airbyte-config/config-models/src/main/java/io/airbyte/config/Configs.java
  airbyte-config/config-models/src/main/java/io/airbyte/config/EnvConfigs.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/JobNotifier.java
  airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/ConnectionsHandler.java
  airbyte-workers/src/main/java/io/airbyte/workers/HttpUtil.java
  airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/activities/JobCreationAndStatusUpdateActivityImpl.java
  docker-compose.yaml
  docs/reference/api/generated-api-html/index.html
Labels: area/platform, area/api, area/server, area/scheduler, area/worker, area/documentation

#70 CU-3epqq8z_Hide-error-log-from-frontend_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/views/Connector/ConnectorCard/ConnectorCard.tsx
Labels: area/platform, team/frontend

#71 CU-864dgrq6d_Select-the-source-or-destination-the-name-prompt-information-contains-airbyte_Abi---
  airbyte-webapp/README.md
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/views/Connector/ConnectorCard/ConnectorCard.tsx
Labels: area/platform, team/frontend

#76 CU-37bxrtt_FE-integrate-with-BE-for-upgrade-plan-functionalities_Muhammad-Akif
  airbyte-webapp/src/App.tsx
  airbyte-webapp/src/components/SideMenu/SideMenu.tsx
  airbyte-webapp/src/components/TabMenu/TabMenu.tsx
  airbyte-webapp/src/components/TabMenu/index.tsx
  airbyte-webapp/src/core/AuthContext/AuthContext.tsx
  airbyte-webapp/src/core/AuthContext/authenticatedUser.ts
  airbyte-webapp/src/core/Constants/roles.ts
  airbyte-webapp/src/core/Constants/statuses.ts
  airbyte-webapp/src/core/domain/payment/Payment.ts
  airbyte-webapp/src/core/domain/payment/PaymentService.tsx
  airbyte-webapp/src/core/domain/payment/index.ts
  airbyte-webapp/src/core/domain/product/Package.ts
  airbyte-webapp/src/core/domain/product/Product.ts
  airbyte-webapp/src/core/domain/product/ProductService.tsx
  airbyte-webapp/src/core/domain/product/index.ts
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/components/PaymentNav.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/SelectPlanPage.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/components/FeaturesCard.tsx
  airbyte-webapp/src/pages/PaymentPage/pages/SelectPlanPage/index.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/BillingAndPaymentPage/BillingAndPaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/BillingAndPaymentPage/components/PaymentForm.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/BillingAndPaymentPage/components/PlanCard.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/BillingAndPaymentPage/components/StripeElements.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/BillingAndPaymentPage/index.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/BillingPaymentStep/BillingPaymentStep.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/BillingPaymentStep/index.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/SelectPlanStep.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/EnterpriseCell.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/FeaturesCard.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/ProcessionalCell.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/Range.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/RangeCard.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/RangeMark.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/index.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/components/MessageBox.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/components/CancelPlanModal.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/components/PlanClause.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/style.module.scss
  airbyte-webapp/src/services/Scope.ts
  airbyte-webapp/src/services/auth/AuthService.ts
  airbyte-webapp/src/services/auth/AuthSpecificationService.tsx
  airbyte-webapp/src/services/payments/PaymentsService.tsx
  airbyte-webapp/src/services/products/ProductsService.tsx
  airbyte-webapp/src/services/workspaces/WorkspacesService.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#78 CU-37bxrtt_FE-integrate-with-BE-for-upgrade-plan-functionalities_Muhammad-Akif
  airbyte-webapp/src/pages/PaymentErrorPage/PaymentErrorPage.tsx
  airbyte-webapp/src/pages/PaymentErrorPage/index.tsx
  airbyte-webapp/src/pages/SettingsPage/components/MessageBox.tsx
  airbyte-webapp/src/pages/routePaths.tsx
  airbyte-webapp/src/pages/routes.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#79 CU-37bxrtt_FE-integrate-with-BE-for-upgrade-plan-functionalities_haimin-
  airbyte-webapp/src/pages/PaymentErrorPage/PaymentErrorPage.tsx
  airbyte-webapp/src/pages/PaymentErrorPage/index.tsx
  airbyte-webapp/src/pages/SettingsPage/components/MessageBox.tsx
  airbyte-webapp/src/pages/routePaths.tsx
  airbyte-webapp/src/pages/routes.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#80 GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA增加到airbyte的source-amazon-selle…
  airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA.json
  airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/source.py
  airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
Labels: area/connectors

#82 CU-864dj93xf_BugIf-the-plan-page-writes-false-it-should-not-be-displayed_Muhammad-Akif
  airbyte-webapp/src/components/MainPageWithScroll/MainPageWithScroll.module.scss
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/components/PlanClause.tsx
Labels: area/platform, team/frontend

#83 CU-860patqtu_Notify-user-when-sync-fails_Roy--
  airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java
  airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/JobPersistence.java
  airbyte-workers/src/main/java/io/airbyte/workers/HttpUtil.java
  airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/activities/JobCreationAndStatusUpdateActivityImpl.java
Labels: area/platform, area/scheduler, area/worker

#84 CU-864dj9697_Bugon-the-settings-page-User-management--account-setting-needs-to-be-hidden-first_haimin-
  airbyte-webapp/src/components/MainPageWithScroll/MainPageWithScroll.module.scss
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/components/PlanClause.tsx
Labels: area/platform, team/frontend

#85 CU-35jyyam_Ability-to-configure-an-existing-connection_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/components/ConnectionSettingsCell.tsx
  airbyte-webapp/src/components/base/Switch/Switch.tsx
Labels: area/platform, team/frontend

#87 CU-864djve4k_BugClick-the-Get-Offer-button-on-the-Upgrade-and-Schedule-page-without-response_Muhammad-Akif
  airbyte-webapp/src/hooks/usePrevstate.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/BillingPaymentStep/BillingPaymentStep.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/EnterpriseCell.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/Mailto.tsx
  airbyte-webapp/src/pages/SettingsPage/components/MessageBox.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/components/CancelPlanModal.tsx
Labels: area/platform, team/frontend

#88 CU-864dkg2f2_Change-airbyte-to-daspire-in-source-amazon-ads_Jerry-Lee---
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.py
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.yaml
Labels: area/connectors

#89 CU-860p9wqzc_Source--destination-pages_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/views/layout/SideBar/SideBar.module.scss
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#90 CU-864djve4k_BugClick-the-Get-Offer-button-on-the-Upgrade-and-Schedule-page-without-response_Muhammad-Akif
  airbyte-webapp/src/core/domain/product/Package.ts
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/FeaturesCard.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/ProfessionalCell.tsx
  airbyte-webapp/src/services/products/ProductsService.tsx
Labels: area/platform, team/frontend

#91 CU-3bfmwqj_Restrictions-based-on-pricing-plan_Roy--
  airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/activities/JobCreationAndStatusUpdateActivityImpl.java
Labels: area/platform, area/worker

#92 CU-864djve4k_BugClick-the-Get-Offer-button-on-the-Upgrade-and-Schedule-page-without-response_Muhammad-Akif
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
Labels: area/platform, team/frontend

#94 CU-35y4khq_Ability-to-copy-a-sourcedestination-and-its-configurations_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/EntityTable/ImplementationTable.tsx
  airbyte-webapp/src/components/EntityTable/components/ConnectionCopyCell.tsx
  airbyte-webapp/src/core/analytics/types.ts
  airbyte-webapp/src/core/domain/connector/DestinationService.ts
  airbyte-webapp/src/core/domain/connector/SourceService.ts
  airbyte-webapp/src/hooks/services/useDestinationHook.tsx
  airbyte-webapp/src/hooks/services/useSourceHook.tsx
  airbyte-webapp/src/locales/en.json
Labels: area/platform, team/frontend

#95 CU-3f7yuy4_Show-notification-settings-from-Airbyte_Abi---
  airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/schemas/GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA.json
  airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/source.py
  airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/streams.py
  airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/DefaultJobPersistence.java
  airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/JobPersistence.java
  airbyte-webapp/README.md
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/ImplementationTable.tsx
  airbyte-webapp/src/components/EntityTable/components/ConnectionCopyCell.tsx
  airbyte-webapp/src/components/EntityTable/components/ConnectionSettingsCell.tsx
  airbyte-webapp/src/components/base/Switch/Switch.tsx
  airbyte-webapp/src/core/analytics/types.ts
  airbyte-webapp/src/core/domain/connector/DestinationService.ts
  airbyte-webapp/src/core/domain/connector/SourceService.ts
  airbyte-webapp/src/hooks/services/useDestinationHook.tsx
  airbyte-webapp/src/hooks/services/useSourceHook.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/NotificationPage/NotificationPage.tsx
  airbyte-webapp/src/views/layout/SideBar/SideBar.module.scss
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
  airbyte-workers/src/main/java/io/airbyte/workers/HttpUtil.java
  airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/activities/JobCreationAndStatusUpdateActivityImpl.java
Labels: area/connectors, area/platform, team/frontend, area/scheduler, area/worker

#97 CU-864dkgrfy_bugThe-prompt-that-the-trial-period-exceeds-14-days-is-wrong_Muhammad-Akif
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
Labels: area/platform, team/frontend

#96 CU-37bxu8u_FE-invite-new-user-UI_Muhammad-Akif
  airbyte-webapp/src/components/base/DropDown/CustomSelect.tsx
  airbyte-webapp/src/components/base/DropDown/DropDown.tsx
  airbyte-webapp/src/components/icons/DeleteIcon.tsx
  airbyte-webapp/src/components/icons/RefreshIcon.tsx
  airbyte-webapp/src/core/domain/role/Role.tsx
  airbyte-webapp/src/core/domain/role/RoleService.tsx
  airbyte-webapp/src/core/domain/role/index.tsx
  airbyte-webapp/src/core/domain/user/User.tsx
  airbyte-webapp/src/core/domain/user/UserService.tsx
  airbyte-webapp/src/core/domain/user/index.tsx
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/AuthPage/UserSignupPage/UserSignupPage.tsx
  airbyte-webapp/src/pages/AuthPage/UserSignupPage/components/SignupForm.module.scss
  airbyte-webapp/src/pages/AuthPage/UserSignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/AuthPage/UserSignupPage/index.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/components/MessageBox.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/ChangeRoleModal.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/DeleteUserModal.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/InviteUserModal.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/UserRoleDropdown.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/UserTable.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/UserTableBody.tsx
  airbyte-webapp/src/pages/routePaths.tsx
  airbyte-webapp/src/pages/routes.tsx
  airbyte-webapp/src/services/roles/RolesService.tsx
  airbyte-webapp/src/services/users/UsersService.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#98 CU-864dkgrfy_bugThe-prompt-that-the-trial-period-exceeds-14-days-is-wrong_Abi---
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.py
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.yaml
  airbyte-webapp/src/core/domain/product/Package.ts
  airbyte-webapp/src/hooks/usePrevstate.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/BillingPaymentStep/BillingPaymentStep.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/EnterpriseCell.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/FeaturesCard.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/Mailto.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/ProfessionalCell.tsx
  airbyte-webapp/src/pages/SettingsPage/components/MessageBox.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/components/CancelPlanModal.tsx
  airbyte-webapp/src/services/products/ProductsService.tsx
Labels: area/connectors, area/platform, team/frontend

#99 CU-35yd1y4_Ability-to-filter-connections-on-dashboard_Roy--
  airbyte-api/src/main/openapi/config.yaml
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/ConnectionsHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendConnectionsHandler.java
  airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/activities/JobCreationAndStatusUpdateActivityImpl.java
Labels: area/platform, area/api, area/server, area/worker
