Repository Yuanrui-Mdt-Info/airbyte, pull requests merged in 2023-03, with the labels that each got.

#164 CU-860q24uw1_Update-statusLang-based-on-backend_Muhammad-Akif
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/utils.tsx
  airbyte-webapp/src/components/JobItem/components/MainInfo.tsx
  airbyte-webapp/src/core/request/AirbyteClient.ts
  airbyte-webapp/src/locales/zh.json
Labels: area/platform, team/frontend

#165 Yuanrui test
  airbyte-webapp/src/App.tsx
  airbyte-webapp/src/components/EmptyResourceListView/EmptyResourceListView.tsx
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/utils.tsx
  airbyte-webapp/src/components/JobItem/components/MainInfo.tsx
  airbyte-webapp/src/core/request/AirbyteClient.ts
  airbyte-webapp/src/locales/zh.json
Labels: area/platform, team/frontend

#166 CU-865bv1gbt_fix-the-issue-that-there-are-no-Chinese-guide-docs-in-localization_Jerry-Lee---
  airbyte-webapp/build.gradle
Labels: area/platform, team/frontend

#168 CU-865bv1zf0_Supplementary-modal-styles_Anet-
  airbyte-webapp/src/components/ConfirmationModal/ConfirmationModal.tsx
  airbyte-webapp/src/components/DocumentationPanel/DocumentationPanel.tsx
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/ImplementationTable.module.scss
  airbyte-webapp/src/components/Modal/Modal.module.scss
  airbyte-webapp/src/components/Modal/Modal.tsx
  airbyte-webapp/src/components/PageTitle/PageTitle.tsx
  airbyte-webapp/src/components/TabMenu/TabMenu.tsx
  airbyte-webapp/src/components/TabMenu/components/TabItem.tsx
  airbyte-webapp/src/components/base/Input/Input.module.scss
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/packages/cloud/views/credits/CreditsPage/CreditsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/ConnectionsTable.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#169 CU-865bv1zf0_Supplementary-modal-styles_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/ConnectorCard/ConnectorCard.tsx
  airbyte-webapp/src/components/base/Input/Input.module.scss
  airbyte-webapp/src/components/base/Input/Input.tsx
  airbyte-webapp/src/components/base/MessageBox/Messagebox.tsx
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.module.scss
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/ConnectionItemPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusMainInfo.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/FeaturesCard.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/RangeCard.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#170 CU-3wm9kwh_FE-notification-settings_Muhammad-Akif
  airbyte-webapp/src/components/TabMenu/TabMenu.tsx
  airbyte-webapp/src/components/icons/NotificationIcon.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/AccountSettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/NotificationPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/index.tsx
Labels: area/platform, team/frontend

#171 CU-860q0kaab_QA-new-webapp-UI_haimin-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/ConfirmationModal/ConfirmationModal.tsx
  airbyte-webapp/src/components/ConnectorCard/ConnectorCard.tsx
  airbyte-webapp/src/components/DocumentationPanel/DocumentationPanel.tsx
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/ImplementationTable.module.scss
  airbyte-webapp/src/components/Modal/Modal.module.scss
  airbyte-webapp/src/components/Modal/Modal.tsx
  airbyte-webapp/src/components/PageTitle/PageTitle.tsx
  airbyte-webapp/src/components/TabMenu/TabMenu.tsx
  airbyte-webapp/src/components/TabMenu/components/TabItem.tsx
  airbyte-webapp/src/components/base/Input/Input.module.scss
  airbyte-webapp/src/components/base/Input/Input.tsx
  airbyte-webapp/src/components/base/MessageBox/Messagebox.tsx
  airbyte-webapp/src/components/icons/NotificationIcon.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/packages/cloud/views/credits/CreditsPage/CreditsPage.tsx
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.module.scss
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/ConnectionsTable.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/ConnectionItemPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusMainInfo.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/FeaturesCard.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/RangeCard.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/AccountSettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/NotificationPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/index.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#172 CU-865bve682_Fix-the-problem-that-the-Tab-component-on-the-SourceDestination-page-is-not-selected_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/TabMenu/TabMenu.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
Labels: area/platform, team/frontend

#174 CU-860pufqey_FE-error-page_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/public/images/octavia/over-error.png
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/views/common/ErrorOccurredView/ErrorOccurredView.module.scss
  airbyte-webapp/src/views/common/ErrorOccurredView/ErrorOccurredView.tsx
Labels: area/platform, team/frontend

#175 CU-865bvv4nz_BugConnectorLast-sync_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/ConnectionStep/ConnectionStep.tsx
  airbyte-webapp/src/components/ConnectionStep/components/StepBox.tsx
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/ImplementationTable.module.scss
  airbyte-webapp/src/components/EntityTable/ImplementationTable.tsx
  airbyte-webapp/src/components/Table/Table.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CopyDestinationPage/CopyDestinationPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CopySourcePage/CopySourcePage.tsx
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.tsx
Labels: area/platform, team/frontend

#176 CU-860q3x77j_New-UI-content-update_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/ConnectorBlocks/DefinitioDetails.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
  airbyte-webapp/src/views/Connector/ServiceForm/FormRoot.tsx
Labels: area/platform, team/frontend

#179 CU-37cb3yh_Amazon-Ads-API-needs-to-upgrade-to-V3_Roy--
  airbyte-integrations/connectors/source-amazon-ads/integration_tests/invalid_config.json
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/report_streams/products_report.py
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/report_streams/report_streams.py
Labels: area/connectors

#181 CU-860pufr44_QA-error-page_haimin-
  airbyte-integrations/connectors/source-amazon-ads/integration_tests/invalid_config.json
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/report_streams/products_report.py
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/report_streams/report_streams.py
  airbyte-webapp/README.md
  airbyte-webapp/public/images/octavia/over-error.png
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/views/common/ErrorOccurredView/ErrorOccurredView.module.scss
  airbyte-webapp/src/views/common/ErrorOccurredView/ErrorOccurredView.tsx
Labels: area/connectors, area/platform, team/frontend

#180 CU-860q3x5uh_Connection-page-UI-improvements_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/EntityTable/ImplementationTable.tsx
  airbyte-webapp/src/components/EntityTable/components/AllConnectionsStatusCell.tsx
  airbyte-webapp/src/components/EntityTable/components/ConnectEntitiesCell.tsx
  airbyte-webapp/src/components/StatusIcon/StatusIcon.tsx
  airbyte-webapp/src/locales/en.json
Labels: area/platform, team/frontend

#182 CU-860pzmhww_eBay-OAuth_Roy--
  airbyte-integrations/connectors/source-ebay/source_ebay/spec.yaml
  airbyte-oauth/src/main/java/io/airbyte/oauth/BaseOAuth2Flow.java
  airbyte-oauth/src/main/java/io/airbyte/oauth/flows/EbayOAuthFlow.java
Labels: area/connectors

#183 CU-865bvygvz_bugModify-webapp-page-display-problem_Muhammad-Akif
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
Labels: area/platform, team/frontend

#184 CU-860q3x5uh_Connection-page-UI-improvements_Anet-
  airbyte-webapp/src/components/EntityTable/components/ConnectEntitiesCell.tsx
  airbyte-webapp/src/components/StatusIcon/StatusIcon.tsx
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
  airbyte-webapp/src/views/common/ErrorOccurredView/ErrorOccurredView.module.scss
Labels: area/platform, team/frontend

#185 CU-860q3x5uh_Connection-page-UI-improvements_Anet-
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
Labels: area/platform, team/frontend

#186 CU-860q3x5uh_Connection-page-UI-improvements_Anet-
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
Labels: area/platform, team/frontend

#187 CU-865bvygvz_bugModify-webapp-page-display-problem_Muhammad-Akif
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/LanguagePage/LanguagePage.tsx
  airbyte-webapp/src/services/users/UsersService.tsx
Labels: area/platform, team/frontend

#189 CU-865bvygvz_bugModify-webapp-page-display-problem_Abi---
  airbyte-webapp/README.md
  airbyte-webapp/src/components/EntityTable/ImplementationTable.tsx
  airbyte-webapp/src/components/EntityTable/components/AllConnectionsStatusCell.tsx
  airbyte-webapp/src/components/EntityTable/components/ConnectEntitiesCell.tsx
  airbyte-webapp/src/components/StatusIcon/StatusIcon.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/LanguagePage/LanguagePage.tsx
  airbyte-webapp/src/services/users/UsersService.tsx
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
  airbyte-webapp/src/views/common/ErrorOccurredView/ErrorOccurredView.module.scss
Labels: area/platform, team/frontend

#188 CU-865bvv4nz_BugConnectorLast-sync_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/ConnectionStep/components/StepBox.tsx
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.tsx
Labels: area/platform, team/frontend

#190 CU-865bvv2a8_bugClick-to-upgrade-subscription-prompt-status-error_Muhammad-Akif
  airbyte-webapp/src/core/Constants/statuses.ts
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.tsx
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/ProfessionalCell.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
Labels: area/platform, team/frontend

#191 CU-860q3x5ze_Overall-size-improvements_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/Breadcrumbs/Breadcrumbs.tsx
  airbyte-webapp/src/components/ConfirmationModal/ConfirmationModal.tsx
  airbyte-webapp/src/components/ConnectionStep/ConnectionStep.tsx
  airbyte-webapp/src/components/ConnectionStep/components/StepBox.tsx
  airbyte-webapp/src/components/ConnectorBlocks/DefinitioDetails.tsx
  airbyte-webapp/src/components/ConnectorBlocks/TableItemTitle.tsx
  airbyte-webapp/src/components/ConnectorCard/ConnectorCard.tsx
  airbyte-webapp/src/components/DataPanel/DefinitionCard.tsx
  airbyte-webapp/src/components/DataPanel/components/Card.tsx
  airbyte-webapp/src/components/DeleteBlock/DeleteBlock.tsx
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/LabeledRadioButton/LabeledRadioButton.tsx
  airbyte-webapp/src/components/LabeledSwitch/LabeledSwitch.tsx
  airbyte-webapp/src/components/Markdown/Markdown.module.scss
  airbyte-webapp/src/components/Modal/Modal.module.scss
  airbyte-webapp/src/components/PageTitle/PageTitle.tsx
  airbyte-webapp/src/components/StepsMenu/components/Step.tsx
  airbyte-webapp/src/components/base/Button/BigButton.tsx
  airbyte-webapp/src/components/base/Switch/Switch.module.scss
  airbyte-webapp/src/components/base/Switch/Switch.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/EnabledControl.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusMainInfo.module.scss
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.module.scss
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/SyncNowButton.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/SelectConnectionPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/ExistingEntityForm.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/TestConnection.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CopyDestinationPage/CopyDestinationPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CopySourcePage/CopySourcePage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/SelectSourcePage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/CreateControls.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/EditControls.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/OperationsSection.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/SyncCatalogField.tsx
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.tsx
  airbyte-webapp/src/views/Connector/ServiceForm/components/CreateControls.tsx
  airbyte-webapp/src/views/Connector/TestConnection/components/TestingSuccess.tsx
Labels: area/platform, team/frontend

#192 CU-865bvv4nz_BugConnectorLast-sync_haimin-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/Breadcrumbs/Breadcrumbs.tsx
  airbyte-webapp/src/components/ConfirmationModal/ConfirmationModal.tsx
  airbyte-webapp/src/components/ConnectionStep/ConnectionStep.tsx
  airbyte-webapp/src/components/ConnectionStep/components/StepBox.tsx
  airbyte-webapp/src/components/ConnectorBlocks/DefinitioDetails.tsx
  airbyte-webapp/src/components/ConnectorBlocks/TableItemTitle.tsx
  airbyte-webapp/src/components/ConnectorCard/ConnectorCard.tsx
  airbyte-webapp/src/components/DataPanel/DefinitionCard.tsx
  airbyte-webapp/src/components/DataPanel/components/Card.tsx
  airbyte-webapp/src/components/DeleteBlock/DeleteBlock.tsx
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/LabeledRadioButton/LabeledRadioButton.tsx
  airbyte-webapp/src/components/LabeledSwitch/LabeledSwitch.tsx
  airbyte-webapp/src/components/Markdown/Markdown.module.scss
  airbyte-webapp/src/components/Modal/Modal.module.scss
  airbyte-webapp/src/components/PageTitle/PageTitle.tsx
  airbyte-webapp/src/components/StepsMenu/components/Step.tsx
  airbyte-webapp/src/components/base/Button/BigButton.tsx
  airbyte-webapp/src/components/base/Switch/Switch.module.scss
  airbyte-webapp/src/components/base/Switch/Switch.tsx
  airbyte-webapp/src/core/Constants/statuses.ts
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/EnabledControl.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusMainInfo.module.scss
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.module.scss
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/SyncNowButton.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/SelectConnectionPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/ExistingEntityForm.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/TestConnection.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CopyDestinationPage/CopyDestinationPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/ProfessionalCell.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CopySourcePage/CopySourcePage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/SelectSourcePage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/CreateControls.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/EditControls.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/OperationsSection.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/SyncCatalogField.tsx
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.tsx
  airbyte-webapp/src/views/Connector/ServiceForm/components/CreateControls.tsx
  airbyte-webapp/src/views/Connector/TestConnection/components/TestingSuccess.tsx
Labels: area/platform, team/frontend

#193 CU-860q3x5ze_Overall-size-improvements_Anet-
  airbyte-webapp/src/components/ConnectionStep/components/StepBox.tsx
  airbyte-webapp/src/components/CreateConnectionContent/CreateConnectionContent.tsx
  airbyte-webapp/src/components/DataPanel/DefinitionCard.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/ExistingEntityForm.tsx
  airbyte-webapp/src/views/Connector/ServiceForm/FormRoot.tsx
  airbyte-webapp/src/views/Connector/TestConnection/components/TestingLoading.tsx
  airbyte-webapp/src/views/Connector/TestConnection/components/TestingSuccess.tsx
Labels: area/platform, team/frontend

#194 CU-860pu1eah_Sign-out-confirmation-message_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#195 CU-860q5erk9_UI-related-changes---addedit-sourcedestination-page_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
Labels: area/platform, team/frontend

#197 CU-865bwq9g8_bugsnowflake_Roy--
  airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
Labels: area/platform, area/server

#198 CU-860q3x77j_New-UI-content-update_haimin-
  airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
  airbyte-webapp/src/components/ConnectionStep/components/StepBox.tsx
  airbyte-webapp/src/components/CreateConnectionContent/CreateConnectionContent.tsx
  airbyte-webapp/src/components/DataPanel/DefinitionCard.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/ExistingEntityForm.tsx
  airbyte-webapp/src/views/Connector/ServiceForm/FormRoot.tsx
  airbyte-webapp/src/views/Connector/TestConnection/components/TestingLoading.tsx
  airbyte-webapp/src/views/Connector/TestConnection/components/TestingSuccess.tsx
Labels: area/platform, team/frontend, area/server

#199 CU-865bx7ga9_bugIn-the-Chinese-state-there-is-an-additional-authority-of-the-account-owner_Muhammad-Akif
  airbyte-webapp/src/core/Constants/roles.ts
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
Labels: area/platform, team/frontend

#200 CU-865bx7ga9_bugIn-the-Chinese-state-there-is-an-additional-authority-of-the-account-owner_Abi---
  airbyte-webapp/src/core/Constants/roles.ts
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
Labels: area/platform, team/frontend

#201 CU-860q5emvg_UI-related-changes---change-plan-page_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/base/Button/Button.tsx
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/BillingPaymentStep/BillingPaymentStep.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/components/CancelPlanModal.tsx
Labels: area/platform, team/frontend

#204 CU-860q5wqdn_Frontend-translation-update_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/ConnectionItemPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/CreationFormPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/SelectConnectionPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/SelectSourcePage.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/EditControls.tsx
Labels: area/platform, team/frontend

#205 CU-860q5xydr_UI-related-changes---config-page-UI_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/CreationFormPage.tsx
Labels: area/platform, team/frontend

#206 CU-865bx1kun_Add-a-source-page-UI-optimization_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/ConnectorBlocks/FormPageContent.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/ConnectionItemPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ReplicationView.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.module.scss
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/CreationFormPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/TestConnection.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CopyDestinationPage/CopyDestinationPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/CreateDestinationPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CopySourcePage/CopySourcePage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/CreateSourcePage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/EditControls.tsx
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.tsx
  airbyte-webapp/src/views/Connector/TestConnection/TestConnection.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#207 CU-37cb3yh_Amazon-Ads-API-needs-to-upgrade-to-V3_Abi---
  airbyte-integrations/connectors/source-ebay/source_ebay/spec.yaml
  airbyte-oauth/src/main/java/io/airbyte/oauth/BaseOAuth2Flow.java
  airbyte-oauth/src/main/java/io/airbyte/oauth/flows/EbayOAuthFlow.java
  airbyte-webapp/README.md
  airbyte-webapp/src/components/ConfirmationModal/ConfirmationModal.tsx
  airbyte-webapp/src/components/ConnectionStep/components/StepBox.tsx
  airbyte-webapp/src/components/ConnectorBlocks/FormPageContent.tsx
  airbyte-webapp/src/components/Modal/Modal.tsx
  airbyte-webapp/src/components/base/Button/Button.tsx
  airbyte-webapp/src/hooks/services/ConfirmationModal/ConfirmationModalService.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/ConnectionItemPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ReplicationView.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.module.scss
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/CreationFormPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/SelectConnectionPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/TestConnection.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CopyDestinationPage/CopyDestinationPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/CreateDestinationPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/BillingPaymentStep/BillingPaymentStep.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/components/CancelPlanModal.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CopySourcePage/CopySourcePage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/CreateSourcePage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/SelectSourcePage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/EditControls.tsx
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.tsx
  airbyte-webapp/src/views/Connector/TestConnection/TestConnection.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/connectors, area/platform, team/frontend

#208 CU-860q3yn8e_Sign-up--sign-in-page-responsiveness_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/icons/GlobIcon.tsx
  airbyte-webapp/src/components/icons/PlusCircleIcon.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.module.scss
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.module.scss
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.module.scss
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/AuthPage/components/FormComponents.tsx
  airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.module.scss
  airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.tsx
Labels: area/platform, team/frontend

#211 CU-860pubrm3_BE-release-NetSuite-as-a-source_Roy--
  airbyte-config/init/src/main/resources/icons/netsuite.svg
  airbyte-config/init/src/main/resources/seed/source_definitions.yaml
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-netsuite/.dockerignore
  airbyte-integrations/connectors/source-netsuite/Dockerfile
  airbyte-integrations/connectors/source-netsuite/README.md
  airbyte-integrations/connectors/source-netsuite/acceptance-test-config.yml
  airbyte-integrations/connectors/source-netsuite/acceptance-test-docker.sh
  airbyte-integrations/connectors/source-netsuite/build.gradle
  airbyte-integrations/connectors/source-netsuite/integration_tests/__init__.py
  airbyte-integrations/connectors/source-netsuite/integration_tests/abnormal_state.json
  airbyte-integrations/connectors/source-netsuite/integration_tests/acceptance.py
  airbyte-integrations/connectors/source-netsuite/integration_tests/configured_catalog.json
  airbyte-integrations/connectors/source-netsuite/integration_tests/test.json
  airbyte-integrations/connectors/source-netsuite/main.py
  airbyte-integrations/connectors/source-netsuite/requirements.txt
  airbyte-integrations/connectors/source-netsuite/sample_files/config.json
  airbyte-integrations/connectors/source-netsuite/sample_files/invalid_config.json
  airbyte-integrations/connectors/source-netsuite/sample_files/sample_state.json
  airbyte-integrations/connectors/source-netsuite/setup.py
  airbyte-integrations/connectors/source-netsuite/source_netsuite/__init__.py
  airbyte-integrations/connectors/source-netsuite/source_netsuite/constraints.py
  airbyte-integrations/connectors/source-netsuite/source_netsuite/errors.py
  airbyte-integrations/connectors/source-netsuite/source_netsuite/source.py
  airbyte-integrations/connectors/source-netsuite/source_netsuite/spec.yaml
  airbyte-integrations/connectors/source-netsuite/source_netsuite/streams.py
  airbyte-integrations/connectors/source-netsuite/unit_tests/__init__.py
  airbyte-integrations/connectors/source-netsuite/unit_tests/test_streams.py
Labels: area/connectors

#212 CU-860q5xydr_UI-related-changes---config-page-UI_haimin-
  airbyte-config/init/src/main/resources/icons/netsuite.svg
  airbyte-config/init/src/main/resources/seed/source_definitions.yaml
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-netsuite/.dockerignore
  airbyte-integrations/connectors/source-netsuite/Dockerfile
  airbyte-integrations/connectors/source-netsuite/README.md
  airbyte-integrations/connectors/source-netsuite/acceptance-test-config.yml
  airbyte-integrations/connectors/source-netsuite/acceptance-test-docker.sh
  airbyte-integrations/connectors/source-netsuite/build.gradle
  airbyte-integrations/connectors/source-netsuite/integration_tests/__init__.py
  airbyte-integrations/connectors/source-netsuite/integration_tests/abnormal_state.json
  airbyte-integrations/connectors/source-netsuite/integration_tests/acceptance.py
  airbyte-integrations/connectors/source-netsuite/integration_tests/configured_catalog.json
  airbyte-integrations/connectors/source-netsuite/integration_tests/test.json
  airbyte-integrations/connectors/source-netsuite/main.py
  airbyte-integrations/connectors/source-netsuite/requirements.txt
  airbyte-integrations/connectors/source-netsuite/sample_files/config.json
  airbyte-integrations/connectors/source-netsuite/sample_files/invalid_config.json
  airbyte-integrations/connectors/source-netsuite/sample_files/sample_state.json
  airbyte-integrations/connectors/source-netsuite/setup.py
  airbyte-integrations/connectors/source-netsuite/source_netsuite/__init__.py
  airbyte-integrations/connectors/source-netsuite/source_netsuite/constraints.py
  airbyte-integrations/connectors/source-netsuite/source_netsuite/errors.py
  airbyte-integrations/connectors/source-netsuite/source_netsuite/source.py
  airbyte-integrations/connectors/source-netsuite/source_netsuite/spec.yaml
  airbyte-integrations/connectors/source-netsuite/source_netsuite/streams.py
  airbyte-integrations/connectors/source-netsuite/unit_tests/__init__.py
  airbyte-integrations/connectors/source-netsuite/unit_tests/test_streams.py
  airbyte-webapp/README.md
  airbyte-webapp/src/components/ConnectionStep/ConnectionStep.tsx
  airbyte-webapp/src/components/base/index.tsx
  airbyte-webapp/src/components/icons/DashIcon.tsx
  airbyte-webapp/src/components/icons/GlobIcon.tsx
  airbyte-webapp/src/components/icons/PlusCircleIcon.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.module.scss
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.module.scss
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.module.scss
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/AuthPage/components/FormComponents.tsx
  airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.module.scss
  airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ReplicationView.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.module.scss
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/SelectConnectionPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/SelectDestinationPage.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/InviteUserModal.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/UserTableBody.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/SelectSourcePage.tsx
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
Labels: area/connectors, area/platform, team/frontend

#213 CU-8669pxbpw_UI-related-changes---error-message-popup_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/Breadcrumbs/Breadcrumbs.tsx
  airbyte-webapp/src/components/SingletonCard/SingletonCard.tsx
  airbyte-webapp/src/components/base/MessageBox/Messagebox.tsx
  airbyte-webapp/src/components/base/index.tsx
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.tsx
Labels: area/platform, team/frontend

#214 CU-860q5erk9_UI-related-changes---addedit-sourcedestination-page_haimin-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/Breadcrumbs/Breadcrumbs.tsx
  airbyte-webapp/src/components/SingletonCard/SingletonCard.tsx
  airbyte-webapp/src/components/base/MessageBox/Messagebox.tsx
  airbyte-webapp/src/components/base/index.tsx
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.module.scss
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.tsx
Labels: area/platform, team/frontend

#215 CU-860q5ff5h_UI-related-changes---stream-table_Anet-
  airbyte-webapp/.env
  airbyte-webapp/README.md
  airbyte-webapp/src/components/SimpleTableComponents/SimpleTableComponents.tsx
  airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.module.scss
  airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.tsx
  airbyte-webapp/src/views/Connection/CatalogTree/StreamHeader.module.scss
  airbyte-webapp/src/views/Connection/CatalogTree/StreamHeader.tsx
  airbyte-webapp/src/views/Connection/CatalogTree/components/PathPopout.tsx
  airbyte-webapp/src/views/Connection/CatalogTree/styles.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/SyncCatalogField.module.scss
  airbyte-webapp/src/views/Connection/ConnectionForm/components/SyncCatalogField.tsx
Labels: area/platform, team/frontend

#216 CU-860q8akf6_eBay-OAuth-redirect_Anet-
  airbyte-webapp/src/hooks/services/useConnectorAuth.tsx
Labels: area/platform, team/frontend

#217 CU-860q8akf6_eBay-OAuth-redirect_Anet-
  airbyte-webapp/src/hooks/services/useConnectorAuth.tsx
Labels: area/platform, team/frontend

#220 CU-860q5ff5h_UI-related-changes---stream-table_haimin-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/SimpleTableComponents/SimpleTableComponents.tsx
  airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.module.scss
  airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.tsx
  airbyte-webapp/src/views/Connection/CatalogTree/StreamHeader.module.scss
  airbyte-webapp/src/views/Connection/CatalogTree/StreamHeader.tsx
  airbyte-webapp/src/views/Connection/CatalogTree/components/PathPopout.tsx
  airbyte-webapp/src/views/Connection/CatalogTree/styles.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/SyncCatalogField.module.scss
  airbyte-webapp/src/views/Connection/ConnectionForm/components/SyncCatalogField.tsx
Labels: area/platform, team/frontend

#222 CU-860q8q04e_Indicate-integration-authentication-status_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/Breadcrumbs/Breadcrumbs.tsx
  airbyte-webapp/src/components/base/DropDown/CustomSelect.tsx
  airbyte-webapp/src/components/base/DropDown/components/Text.tsx
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.module.scss
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.module.scss
  airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/useOauthFlowAdapter.tsx
Labels: area/platform, team/frontend

#223 CU-860q8q04e_Indicate-integration-authentication-status_Abi---
  airbyte-webapp/README.md
  airbyte-webapp/src/components/Breadcrumbs/Breadcrumbs.tsx
  airbyte-webapp/src/components/base/DropDown/CustomSelect.tsx
  airbyte-webapp/src/components/base/DropDown/components/Text.tsx
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.module.scss
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.module.scss
  airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/useOauthFlowAdapter.tsx
Labels: area/platform, team/frontend

#224 CU-3wm9kcb_QA-usage-notification--settings_Abi---
  airbyte-webapp/src/App.tsx
  airbyte-webapp/src/components/Modal/Modal.tsx
  airbyte-webapp/src/config/defaultConfig.ts
  airbyte-webapp/src/core/domain/notificationSetting/notificationSettingService.tsx
  airbyte-webapp/src/core/request/AirbyteClient.ts
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/hooks/services/AppNotification/AppNotificationProvider.tsx
  airbyte-webapp/src/hooks/services/AppNotification/index.tsx
  airbyte-webapp/src/hooks/services/Health/HealthPollService.tsx
  airbyte-webapp/src/hooks/services/Health/HealthProvider.tsx
  airbyte-webapp/src/hooks/services/Health/index.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/packages/cloud/views/settings/CloudSettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/components/MessageBox.tsx
  airbyte-webapp/src/pages/SettingsPage/index.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/AccountSettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/LanguagePage/LanguagePage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/NotificationPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/components/NotificationFlag.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/components/StyledTable.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/components/SyncTable.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/components/UsageTable.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/components/UsageTableRow.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/icons/addIcon.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/icons/index.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/icons/removeIcon.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/InviteUserModal.tsx
  airbyte-webapp/src/pages/routes.tsx
  airbyte-webapp/src/scss/_variables.scss
  airbyte-webapp/src/services/notificationSetting/NotificationSettingService.tsx
  airbyte-webapp/src/views/layout/Banners/BillingWarningBanner/BillingWarningBanner.tsx
  airbyte-webapp/src/views/layout/Banners/BillingWarningBanner/index.tsx
  airbyte-webapp/src/views/layout/Banners/SyncNotificationBanner/SyncNotificationBanner.tsx
  airbyte-webapp/src/views/layout/Banners/SyncNotificationBanner/components/IgnoreNotificationModal.tsx
  airbyte-webapp/src/views/layout/Banners/SyncNotificationBanner/icons/crossIcon.tsx
  airbyte-webapp/src/views/layout/Banners/SyncNotificationBanner/index.tsx
  airbyte-webapp/src/views/layout/Banners/UpgradePlanBanner/UpgradePlanBanner.tsx
  airbyte-webapp/src/views/layout/Banners/UpgradePlanBanner/components/UnauthorizedModal.tsx
  airbyte-webapp/src/views/layout/Banners/UpgradePlanBanner/index.tsx
  airbyte-webapp/src/views/layout/Banners/banners.module.scss
  airbyte-webapp/src/views/layout/Banners/index.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
  airbyte-webapp/src/views/layout/SideBar/SideBar.module.scss
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#225 CU-865bzm9y0_bugAfter-clicking-Add-the-default-30-error-is-displayed_Muhammad-Akif
  airbyte-webapp/src/locales/zh.json
Labels: area/platform, team/frontend

#226 CU-860q2g5w4_Sign-up--sign-in-page-language-switch_Muhammad-Akif
  airbyte-webapp/src/core/request/AirbyteRequestService.ts
  airbyte-webapp/src/pages/AuthPage/GoogleAuthBtn/GoogleAuthBtn.tsx
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.module.scss
  airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/LanguagePage/LanguagePage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/LanguagePage/components/LanguageDropdown.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
  airbyte-webapp/src/services/auth/AuthService.ts
Labels: area/platform, team/frontend

#227 CU-860q8ckbw_Connection-config-update_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/ConnectorCard/ConnectorCard.tsx
  airbyte-webapp/src/components/icons/CrossIcon.tsx
  airbyte-webapp/src/components/icons/TickIcon.tsx
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ConnectionName.module.scss
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ConnectionName.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ConnectionPageTitle.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusMainInfo.module.scss
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusMainInfo.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/SyncNowButton.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
Labels: area/platform, team/frontend

#228 Cu 860q8qcuf net suite sync issue carlos
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-netsuite/integration_tests/configured_catalog.json
  airbyte-integrations/connectors/source-netsuite/sample_files/config.json
  airbyte-integrations/connectors/source-netsuite/source_netsuite/source.py
  airbyte-integrations/connectors/source-netsuite/source_netsuite/spec.yaml
  airbyte-integrations/connectors/source-netsuite/source_netsuite/streams.py
  docs/setup-guide/sources/netsuite.md
  docs/zh/setup-guide/sources/netsuite.md
Labels: area/connectors, area/documentation

#229 CU-860q9u73q_UI-when-there-is-no-sourcedestination_Anet-
  airbyte-webapp/.eslintrc
  airbyte-webapp/README.md
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
Labels: area/platform, team/frontend

#230 CU-8669f246r_QA-NetSuite_haimin-
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-netsuite/integration_tests/configured_catalog.json
  airbyte-integrations/connectors/source-netsuite/sample_files/config.json
  airbyte-integrations/connectors/source-netsuite/source_netsuite/source.py
  airbyte-integrations/connectors/source-netsuite/source_netsuite/spec.yaml
  airbyte-integrations/connectors/source-netsuite/source_netsuite/streams.py
  airbyte-webapp/.eslintrc
  airbyte-webapp/README.md
  airbyte-webapp/src/components/ConnectorCard/ConnectorCard.tsx
  airbyte-webapp/src/components/icons/CrossIcon.tsx
  airbyte-webapp/src/components/icons/TickIcon.tsx
  airbyte-webapp/src/core/request/AirbyteRequestService.ts
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/AuthPage/GoogleAuthBtn/GoogleAuthBtn.tsx
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.module.scss
  airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ConnectionName.module.scss
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ConnectionName.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ConnectionPageTitle.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusMainInfo.module.scss
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusMainInfo.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/SyncNowButton.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/LanguagePage/LanguagePage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/LanguagePage/components/LanguageDropdown.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
  airbyte-webapp/src/services/auth/AuthService.ts
  airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
  docker-compose.yaml
  docs/setup-guide/sources/netsuite.md
  docs/zh/setup-guide/sources/netsuite.md
Labels: area/connectors, area/platform, team/frontend, area/documentation

#231 CU-865bztzh0_bugOn-the-setting-page-icons-and-texts-should-be-aligned-respectively_Muhammad-Akif
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/NotificationPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/components/NotificationFlag.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/components/SyncTable.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/components/UsageTable.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/components/UsageTableRow.tsx
Labels: area/platform, team/frontend

#232 CU-865bz04vx_Too-many-paginations_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/Pagination/Pagination.tsx
  airbyte-webapp/src/views/layout/Banners/UpgradePlanBanner/UpgradePlanBanner.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#233 NetSuite 文档修改
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-netsuite/source_netsuite/spec.yaml
  docs/setup-guide/sources/netsuite.md
  docs/zh/setup-guide/sources/netsuite.md
Labels: area/connectors, area/documentation

#234 CU-3bfn01d_FE-optimization-when-plan-runs-out_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/ConfirmationModal/ConfirmationModal.tsx
  airbyte-webapp/src/core/request/requestStatusCode.ts
  airbyte-webapp/src/hooks/services/ConfirmationModal/ConfirmationModalService.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/ConnectionsTable.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpdateStatusError.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/ConnectionItemPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/EnabledControl.tsx
  airbyte-webapp/src/views/Connector/ServiceForm/ServiceForm.tsx
  airbyte-webapp/src/views/layout/Banners/UpgradePlanBanner/UpgradePlanBanner.tsx
Labels: area/platform, team/frontend

#236 CU-860pg6mde_Plan-selection-slider-issues_Muhammad-Akif
  airbyte-oauth/src/main/java/io/airbyte/oauth/flows/EbayOAuthFlow.java
  airbyte-webapp/package-lock.json
  airbyte-webapp/package.json
  airbyte-webapp/src/core/domain/product/Product.ts
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/SelectPlanStep.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/FeaturesCard.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/ProfessionalCell.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/RangeCard.tsx
  airbyte-webapp/src/services/products/ProductsService.tsx
Labels: area/platform, team/frontend

#235 CU-8669f246a_BE-release-ClickHouse-as-a-destination_Roy--
  airbyte-config/init/src/main/resources/seed/destination_definitions.yaml
  airbyte-config/init/src/main/resources/seed/destination_specs.yaml
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/destination-clickhouse/src/main/resources/spec.json
  docs/setup-guide/destinations/clickhouse.md
  docs/zh/setup-guide/destinations/clickhouse.md
Labels: area/connectors, area/documentation

#237 CU-860q9v4ad_UI-issues-with-banner_Muhammad-Akif
  airbyte-webapp/src/views/layout/Banners/UpgradePlanBanner/UpgradePlanBanner.tsx
Labels: area/platform, team/frontend

#240 CU-865c05nzg_bugWhen-I-click-to-close-the-prompt-it-still-shows_Muhammad-Akif
  airbyte-webapp/src/core/domain/notificationSetting/notificationSettingService.tsx
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/services/notificationSetting/NotificationSettingService.tsx
  airbyte-webapp/src/views/layout/Banners/SyncNotificationBanner/components/IgnoreNotificationModal.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#241 CU-865c10u8z_bugAfter-choosing-to-unsubscribe-this-button-is-still-displayed-and-has-not-been-refreshed-in-time_Muhammad-Akif
  airbyte-webapp/src/components/base/Button/BigButton.tsx
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/views/layout/Banners/UpgradePlanBanner/UpgradePlanBanner.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#242 CU-8669fb1at_Add-Fullstory-snippet-to-webapp_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/public/index.html
  airbyte-webapp/src/config/defaultConfig.ts
Labels: area/platform, team/frontend

#244 CU-860pubrn7_QA-ClickHouse_haimin-
  airbyte-webapp/README.md
  airbyte-webapp/public/index.html
  airbyte-webapp/src/components/icons/DocumentationArrowIcon.tsx
  airbyte-webapp/src/components/icons/DocumentationIcon.tsx
  airbyte-webapp/src/config/defaultConfig.ts
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/AccountSettingsPage.tsx
  airbyte-webapp/src/pages/routePaths.tsx
  airbyte-webapp/src/views/layout/SideBar/SideBar.module.scss
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#245 CU-865c13jp9_bugShould-be-modified-according-to-the-prototypeClick-the-button-to-contact-sales-and-jump-to-our-email-supportdaspirecom_Muhammad-Akif
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/FeaturesCard.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/ProfessionalCell.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/Range.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/RangeCard.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/RangeMark.tsx
Labels: area/platform, team/frontend

#246 CU-860qbjnqd_Change-the-sign-out-icon_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/SignOutIcon.tsx
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#247 CU-860qc62mb_Update-translation_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/public/index.html
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#248 CU-8669f246r_QANetSuite_haimin-
  airbyte-webapp/README.md
  airbyte-webapp/public/index.html
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/SignOutIcon.tsx
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#249 CU-860qc62mb_Update-translation_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/public/index.html
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#250 CU-865c1bz78_bug_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpdateStatusError.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
  airbyte-webapp/src/views/layout/Banners/BillingWarningBanner/BillingWarningBanner.tsx
Labels: area/platform, team/frontend

#251 CU-865c06dzy_bugCompleted-notification-not-shown-when-sync-succeeds-or-fails_Muhammad-Akif
  airbyte-webapp/src/hooks/services/Health/HealthPollService.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/SettingsPage/components/MessageBox.tsx
Labels: area/platform, team/frontend

#252 CU-865c1kmc3_bugWhen-clicking-to-add-a-new-usage-limit-mail-and-app-notifications-should-be-turned-on-by-default_Muhammad-Akif
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/NotificationPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/components/NotificationFlag.tsx
Labels: area/platform, team/frontend

#254 CU-865c1kkgr_bugCheck-No-more-reminders-during-this-billing-cycle-and-then-click-Upgrade-Now-to-jump-to-the-upgrade-plan-page-and-the-banner-should-not-be-displayed_Muhammad-Akif
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#255 CU-865c1kkgr_bugCheck-No-more-reminders-during-this-billing-cycle-and-then-click-Upgrade-Now-to-jump-to-the-upgrade-plan-page-and-the-banner-should-not-be-displayed_Abi---
  airbyte-webapp/README.md
  airbyte-webapp/src/hooks/services/Health/HealthPollService.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpdateStatusError.tsx
  airbyte-webapp/src/pages/SettingsPage/components/MessageBox.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/NotificationPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/components/NotificationFlag.tsx
  airbyte-webapp/src/views/layout/Banners/BillingWarningBanner/BillingWarningBanner.tsx
  airbyte-webapp/src/views/layout/Banners/SyncNotificationBanner/SyncNotificationBanner.tsx
  airbyte-webapp/src/views/layout/Banners/SyncNotificationBanner/components/IgnoreNotificationModal.tsx
Labels: area/platform, team/frontend

#257 CU-865c06dzy_bugCompleted-notification-not-shown-when-sync-succeeds-or-fails_Muhammad-Akif
  airbyte-webapp/src/hooks/services/Health/HealthPollService.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
Labels: area/platform, team/frontend

#259 CU-866a057uj_Pricing-page-font-weight_Muhammad-Akif
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
Labels: area/platform, team/frontend

#260 CU-866a05878_Sourcedestinationconnection-test-page-UI_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/core/domain/connector/SourceService.ts
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/TestConnection.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CopyDestinationPage/CopyDestinationPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/components/HeaderSection.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CopySourcePage/CopySourcePage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/CreateSourcePage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/components/HeaderSection.tsx
  airbyte-webapp/src/views/Connector/ConnectorCard/ConnectorCard.tsx
  airbyte-webapp/src/views/Connector/ConnectorCard/useTestConnector.tsx
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.tsx
  airbyte-webapp/src/views/Connector/TestConnection/TestConnection.tsx
Labels: area/platform, team/frontend

#261 CU-3u4cfum_FE-email--verify-screen-UI_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/Link/Link.tsx
  airbyte-webapp/src/components/base/MessageBox/Messagebox.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.module.scss
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/ResetPasswordPage/ResetPasswordPage.module.scss
  airbyte-webapp/src/pages/AuthPage/ResetPasswordPage/ResetPasswordPage.tsx
  airbyte-webapp/src/pages/AuthPage/ResetPasswordPage/components/CheckEmailSuccessful.tsx
  airbyte-webapp/src/pages/AuthPage/ResetPasswordPage/components/ForgotPasswordForm.tsx
  airbyte-webapp/src/pages/AuthPage/ResetPasswordPage/components/ResetPasswordForm.tsx
  airbyte-webapp/src/pages/AuthPage/ResetPasswordPage/components/common.tsx
  airbyte-webapp/src/pages/AuthPage/ResetPasswordPage/index.tsx
  airbyte-webapp/src/pages/AuthPage/VerifyEmailPage/VerifyEmailPage.module.scss
  airbyte-webapp/src/pages/AuthPage/VerifyEmailPage/VerifyEmailPage.tsx
  airbyte-webapp/src/pages/AuthPage/VerifyEmailPage/components/LogoIcon.tsx
  airbyte-webapp/src/pages/AuthPage/VerifyEmailPage/index.tsx
  airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.module.scss
  airbyte-webapp/src/pages/routePaths.tsx
  airbyte-webapp/src/pages/routes.tsx
Labels: area/platform, team/frontend
