Repository Yuanrui-Mdt-Info/airbyte, pull requests merged in 2023-02, with the labels that each got.

#122 CU-860pme6my_Bug-not-able-to-sign-up-sign-in-with-Google_Muhammad-Akif
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/UserRoleDropdown.tsx
Labels: area/platform, team/frontend

#123 CU-860pme6my_Bug-not-able-to-sign-up-sign-in-with-Google_Abi---
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/UserRoleDropdown.tsx
Labels: area/platform, team/frontend

#125 CU-860pk0t80_FE-change-wording-in-Alpha-connectors_Abi---
  airbyte-webapp/README.md
  airbyte-webapp/src/config/links.ts
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/views/Connector/ServiceForm/components/WarningMessage.tsx
Labels: area/platform, team/frontend

#127 CU-860pu0r0k_Release-Shopify-as-a-source_Roy--
  airbyte-config/init/src/main/resources/seed/source_definitions.yaml
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-shopify/Dockerfile
  airbyte-integrations/connectors/source-shopify/source_shopify/spec.json
Labels: area/connectors

#128 CU-860pe7vb3_New-source-Walmart_haimin-
  airbyte-config/init/src/main/resources/seed/source_definitions.yaml
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-shopify/Dockerfile
  airbyte-integrations/connectors/source-shopify/source_shopify/spec.json
  docs/setup-guide/sources/amazon-ads.md
  docs/setup-guide/sources/amazon-seller-partner.md
  docs/setup-guide/sources/mysql.md
  docs/setup-guide/sources/netsuite.md
  docs/setup-guide/sources/walmart-marketplace.md
Labels: area/connectors, area/documentation

#130 CU-860pu0r0k_Release-Shopify-as-a-source_Abi---
  airbyte-integrations/connectors/source-shopify/integration_tests/configured_catalog.json
  airbyte-integrations/connectors/source-shopify/integration_tests/invalid_config.json
  airbyte-integrations/connectors/source-shopify/source_shopify/schemas/order_refunds.json
  airbyte-integrations/connectors/source-shopify/source_shopify/schemas/orders.json
  airbyte-integrations/connectors/source-shopify/source_shopify/source.py
  docs/setup-guide/sources/shopify.md
  kube/overlays/dev-integration-test/.env
  kube/overlays/dev-integration-test/.secrets
  kube/overlays/dev-integration-test/kustomization.yaml
  kube/overlays/dev-integration-test/parallelize-worker.yaml
  kube/resources-dev/admin-service-account.yaml
  kube/resources-dev/airbyte-minio.yaml
  kube/resources-dev/bootloader.yaml
  kube/resources-dev/cron.yaml
  kube/resources-dev/db.yaml
  kube/resources-dev/kustomization.yaml
  kube/resources-dev/pod-sweeper.yaml
  kube/resources-dev/secret-gcs-log-creds.yaml
  kube/resources-dev/server.yaml
  kube/resources-dev/temporal.yaml
  kube/resources-dev/volume-configs.yaml
  kube/resources-dev/volume-db.yaml
  kube/resources-dev/webapp.yaml
  kube/resources-dev/worker.yaml
Labels: area/connectors, area/platform, kubernetes, area/documentation

#131 CU-3pqm6zx_Ability-to-use-auth-to-set-up-Amazon-Ads--SP_Muhammad-Akif
  airbyte-webapp/src/config/defaultConfig.ts
  airbyte-webapp/src/hooks/services/Feature/constants.ts
  airbyte-webapp/src/hooks/services/useConnectorAuth.tsx
  airbyte-webapp/src/pages/AuthPage/GoogleAuthBtn/GoogleAuthBtn.tsx
  airbyte-webapp/src/utils/connectors/constants.ts
  airbyte-webapp/src/utils/connectors/destinations.json
  airbyte-webapp/src/utils/connectors/index.ts
  airbyte-webapp/src/utils/connectors/sources.json
  airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/AuthButton.tsx
Labels: area/platform, team/frontend

#132 CU-3pqm6zx_Ability-to-use-auth-to-set-up-Amazon-Ads--SP_Abi---
  airbyte-webapp/src/config/defaultConfig.ts
  airbyte-webapp/src/hooks/services/Feature/constants.ts
  airbyte-webapp/src/hooks/services/useConnectorAuth.tsx
  airbyte-webapp/src/pages/AuthPage/GoogleAuthBtn/GoogleAuthBtn.tsx
  airbyte-webapp/src/utils/connectors/constants.ts
  airbyte-webapp/src/utils/connectors/destinations.json
  airbyte-webapp/src/utils/connectors/index.ts
  airbyte-webapp/src/utils/connectors/sources.json
  airbyte-webapp/src/views/Connector/ServiceForm/components/Sections/auth/AuthButton.tsx
Labels: area/platform, team/frontend

#134 CU-3pqm6zx_Ability-to-use-auth-to-set-up-Amazon-Ads--SP_Muhammad-Akif
  airbyte-webapp/src/config/defaultConfig.ts
  airbyte-webapp/src/hooks/services/useConnectorAuth.tsx
Labels: area/platform, team/frontend

#136 CU-865bpydm0__Roy--
  airbyte-api/src/main/openapi/config.yaml
  airbyte-server/src/main/java/io/airbyte/server/handlers/ConnectionsHandler.java
Labels: area/platform, area/api, area/server

#138 CU-37c0c41_FE-integrate-with-BE-for-filter-functionalities_Muhammad-Akif
  airbyte-webapp/src/components/Pagination/Pagination.tsx
  airbyte-webapp/src/core/domain/connection/WebBackendConnectionService.ts
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/hooks/services/useDestinationHook.tsx
  airbyte-webapp/src/hooks/services/useSourceHook.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
Labels: area/platform, team/frontend

#140 CU-8669e63p3_Button-in-a-wired-place_Muhammad-Akif
  airbyte-webapp/src/components/PageTitle/PageTitle.tsx
  airbyte-webapp/src/core/request/AirbyteClient1.ts
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#142 CU-86698rq7v_eBay_Abi---
  airbyte-webapp/src/components/PageTitle/PageTitle.tsx
  airbyte-webapp/src/components/Pagination/Pagination.tsx
  airbyte-webapp/src/core/domain/connection/WebBackendConnectionService.ts
  airbyte-webapp/src/core/request/AirbyteClient1.ts
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/hooks/services/useDestinationHook.tsx
  airbyte-webapp/src/hooks/services/useSourceHook.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/UpgradePlanBar.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#143 CU-860pg5eke_Button-styles-on-click-should-be-the-same_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/views/layout/SideBar/SideBar.module.scss
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#145 CU-865bqcaw1_BugUser-management-page-small-screen-automatic-adaptation-problem_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/base/DropDown/CustomSelect.tsx
Labels: area/platform, team/frontend

#146 CU-865btacyp_BugDouble-click-the-dashboard-to-report-an-error_Muhammad-Akif
  airbyte-webapp/src/App.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#147 CU-865bqm1p4_Airbyte_Roy--
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-ebay/integration_tests/catalog.json
  airbyte-integrations/connectors/source-ebay/source_ebay/source.py
  airbyte-integrations/connectors/source-ebay/source_ebay/spec.yaml
  docs/setup-guide/destinations/mysql.md
  docs/setup-guide/sources/amazon-ads.md
  docs/setup-guide/sources/amazon-seller-partner.md
  docs/setup-guide/sources/mysql.md
  docs/setup-guide/sources/shopify.md
  docs/zh/setup-guide/destinations/bigquery.md
  docs/zh/setup-guide/destinations/mysql.md
  docs/zh/setup-guide/destinations/redshift.md
  docs/zh/setup-guide/destinations/snowflake.md
  docs/zh/setup-guide/sources/amazon-ads.md
  docs/zh/setup-guide/sources/amazon-seller-partner.md
  docs/zh/setup-guide/sources/bigcommerce.md
  docs/zh/setup-guide/sources/ebay.md
  docs/zh/setup-guide/sources/mysql.md
  docs/zh/setup-guide/sources/netsuite.md
  docs/zh/setup-guide/sources/shopify.md
  docs/zh/setup-guide/sources/walmart-marketplace.md
  docs/zh/setup-guide/sources/woocommerce.md
Labels: area/connectors, area/documentation

#148 CU-865btmgq6_bugebay_Roy--
  airbyte-integrations/connectors/source-ebay/source_ebay/source.py
Labels: area/connectors

#149 CU-865btb6y4_BugWhen-no-matching-result-redirected-to-create-the-first-connection-page_Muhammad-Akif
  airbyte-webapp/src/components/LoadingPage/LoadingPage.tsx
  airbyte-webapp/src/components/Table/Table.tsx
  airbyte-webapp/src/components/base/DropDown/DropDown.tsx
  airbyte-webapp/src/core/domain/connection/WebBackendConnectionService.ts
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/hooks/services/useDestinationHook.tsx
  airbyte-webapp/src/hooks/services/useSourceHook.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/ConnectionPage/ConnectionPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
Labels: area/platform, team/frontend

#151 CU-865bqm1p4_Airbyte_Roy--
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/ConnectionsHandler.java
Labels: area/platform, area/server

#154 CU-860q0x3j9_Setup-guide-display-language_Muhammad-Akif
  airbyte-webapp/src/components/EmptyResourceListView/EmptyResourceListView.tsx
  airbyte-webapp/src/config/defaultConfig.ts
  airbyte-webapp/src/config/links.ts
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/packages/cloud/views/auth/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.module.scss
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.module.scss
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/AuthPage/UserSignupPage/components/SignupForm.module.scss
  airbyte-webapp/src/pages/AuthPage/UserSignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/BillingPaymentStep/BillingPaymentStep.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/ProfessionalCell.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/LanguagePage/LanguagePage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/components/CancelPlanModal.tsx
Labels: area/platform, team/frontend

#155 CU-865bqm1p4_Airbyte_Roy--
  docs/zh/setup-guide/destinations/bigquery.md
  docs/zh/setup-guide/destinations/mysql.md
  docs/zh/setup-guide/destinations/redshift.md
  docs/zh/setup-guide/destinations/snowflake.md
  docs/zh/setup-guide/sources/amazon-ads.md
  docs/zh/setup-guide/sources/amazon-seller-partner.md
  docs/zh/setup-guide/sources/bigcommerce.md
  docs/zh/setup-guide/sources/ebay.md
  docs/zh/setup-guide/sources/mysql.md
  docs/zh/setup-guide/sources/netsuite.md
  docs/zh/setup-guide/sources/shopify.md
  docs/zh/setup-guide/sources/walmart-marketplace.md
  docs/zh/setup-guide/sources/woocommerce.md
Labels: area/documentation

#159 CU-860q24r40_Frontend-deployment-issue-debug_Muhammad-Akif
  airbyte-webapp/src/App.tsx
Labels: area/platform, team/frontend

#162 CU-860q2g487_Clicking-on-destination-resulting-in-error_Muhammad-Akif
  airbyte-webapp/src/components/EmptyResourceListView/EmptyResourceListView.tsx
Labels: area/platform, team/frontend

#163 CU-8669fca66_Source-details-page_Anet-
  airbyte-webapp/src/components/base/Input/Input.module.scss
  airbyte-webapp/src/components/base/Tooltip/Tooltip.module.scss
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusMainInfo.module.scss
  airbyte-webapp/src/scss/_colors.scss
Labels: area/platform, team/frontend
