Repository Yuanrui-Mdt-Info/airbyte, pull requests merged in 2023-04, with the labels that each got.

#262 CU-3u4cfum_FE-email--verify-screen-UI_Anet-
  airbyte-webapp/src/locales/zh.json
Labels: area/platform, team/frontend

#263 CU-866a0pjt6_Bug-banner-shows-wrong-message_Muhammad-Akif
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
Labels: area/platform, team/frontend

#264 CU-866a0p8kr_QA-webapp-UI-updates_haimin-
  airbyte-integrations/bases/base-normalization/dbt-project-template/macros/should_full_refresh.sql
  airbyte-integrations/bases/base-normalization/entrypoint.sh
  airbyte-integrations/bases/base-normalization/normalization/transform_catalog/stream_processor.py
  airbyte-webapp/README.md
  airbyte-webapp/src/components/Link/Link.tsx
  airbyte-webapp/src/components/base/MessageBox/Messagebox.tsx
  airbyte-webapp/src/core/domain/connector/SourceService.ts
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.module.scss
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/ResetPasswordPage/ResetPasswordPage.module.scss
  airbyte-webapp/src/pages/AuthPage/ResetPasswordPage/ResetPasswordPage.tsx
  airbyte-webapp/src/pages/AuthPage/ResetPasswordPage/components/CheckEmailSuccessful.tsx
  airbyte-webapp/src/pages/AuthPage/ResetPasswordPage/components/ForgotPasswordForm.tsx
  airbyte-webapp/src/pages/AuthPage/ResetPasswordPage/components/ResetPasswordForm.tsx
  airbyte-webapp/src/pages/AuthPage/ResetPasswordPage/components/common.tsx
  airbyte-webapp/src/pages/AuthPage/ResetPasswordPage/index.tsx
  airbyte-webapp/src/pages/AuthPage/VerifyEmailPage/VerifyEmailPage.module.scss
  airbyte-webapp/src/pages/AuthPage/VerifyEmailPage/VerifyEmailPage.tsx
  airbyte-webapp/src/pages/AuthPage/VerifyEmailPage/components/LogoIcon.tsx
  airbyte-webapp/src/pages/AuthPage/VerifyEmailPage/index.tsx
  airbyte-webapp/src/pages/AuthPage/components/FormHeaderSection.module.scss
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/TestConnection.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CopyDestinationPage/CopyDestinationPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/components/HeaderSection.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CopySourcePage/CopySourcePage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/CreateSourcePage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/components/HeaderSection.tsx
  airbyte-webapp/src/pages/routePaths.tsx
  airbyte-webapp/src/pages/routes.tsx
  airbyte-webapp/src/views/Connector/ConnectorCard/ConnectorCard.tsx
  airbyte-webapp/src/views/Connector/ConnectorCard/useTestConnector.tsx
  airbyte-webapp/src/views/Connector/ConnectorDocumentationLayout/ConnectorDocumentationLayout.tsx
  airbyte-webapp/src/views/Connector/TestConnection/TestConnection.tsx
Labels: area/platform, team/frontend, normalization

#265 CU-866a0pjt6_Bug-banner-shows-wrong-message_Muhammad-Akif
  airbyte-webapp/src/views/layout/Banners/UpgradePlanBanner/UpgradePlanBanner.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#266 CU-860puckwp_FE-change-password-UI_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/AuthPage/components/FormComponents.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/AccountSettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/AccountPage/AccountPage.module.scss
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/AccountPage/AccountPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/LanguagePage/components/LanguageDropdown.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/NotificationPage/NotificationPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/PasswordPage/PasswordPage.module.scss
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/PasswordPage/PasswordPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/SupportPage/SupportPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/SupportPage/components/EmailIcon.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/SupportPage/components/SubmitSuccess.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/SupportPage/components/SupportForm.module.scss
  airbyte-webapp/src/pages/SettingsPage/pages/SupportPage/components/SupportForm.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/SupportPage/components/type.ts
  airbyte-webapp/src/pages/SettingsPage/pages/SupportPage/index.tsx
  airbyte-webapp/src/pages/routePaths.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#268 CU-866a1ppxu_Icon-and-name-will-overlap-if-name-is-long_Muhammad-Akif
  airbyte-webapp/src/components/ConnectorCard/ConnectorCard.tsx
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/components/ConnectorCell.tsx
  airbyte-webapp/src/components/EntityTable/components/NameCell.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ConnectionName.module.scss
Labels: area/platform, team/frontend

#270 CU-865c46fn4_Fix-the-issue-on-airbyte-yuanrui-test-branch_Muhammad-Akif
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#272 CU-866a1pr5c_Change-the-scrollbar-to-custom-scroll-instead-of-browser-default_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/base/DropDown/components/Menu.tsx
  airbyte-webapp/src/components/base/DropDown/components/Option.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
Labels: area/platform, team/frontend

#273 CU-866a1pr5c_Change-the-scrollbar-to-custom-scroll-instead-of-browser-default_Abi---
  airbyte-webapp/README.md
  airbyte-webapp/src/components/base/DropDown/components/Menu.tsx
  airbyte-webapp/src/components/base/DropDown/components/Option.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
Labels: area/platform, team/frontend

#274 CU-865c4ha9v_bugIn-Chinese-the-prompt-information-is-incorrect-when-selecting-a-resource-that-has-no-synchronization-record_Muhammad-Akif
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/pages/LanguagePage/LanguagePage.tsx
  airbyte-webapp/src/views/layout/Banners/UpgradePlanBanner/UpgradePlanBanner.tsx
Labels: area/platform, team/frontend

#275 Amazon Ads/SP region & marketplace selection
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.py
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.yaml
  airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/source.py
  airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/spec.py
  airbyte-oauth/src/main/java/io/airbyte/oauth/flows/AmazonAdsOAuthFlow.java
  airbyte-oauth/src/main/java/io/airbyte/oauth/flows/AmazonSellerPartnerOAuthFlow.java
Labels: area/connectors

#276 CU-865c4qed1_The-b-tag-should-not-be-displayed-in-the-description_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/ReleaseStageBadge/ReleaseStageBadge.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/SyncCatalogField.tsx
Labels: area/platform, team/frontend

#277 CU-865c4t3aq_Click-Back-on-the-card-number-information-filling-page-the-returned-page-is-incorrect_Anet-
  airbyte-webapp/src/pages/PaymentErrorPage/PaymentErrorPage.tsx
Labels: area/platform, team/frontend

#278 CU-865c4t3aq_Click-Back-on-the-card-number-information-filling-page-the-returned-page-is-incorrect_Anet-
  airbyte-webapp/src/pages/PaymentErrorPage/PaymentErrorPage.tsx
Labels: area/platform, team/frontend

#280 CU-866a3f4yf_QA-Amazon-AdsSP-region-selection_haimin-
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.py
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/spec.yaml
  airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/source.py
  airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/spec.py
  airbyte-oauth/src/main/java/io/airbyte/oauth/flows/AmazonAdsOAuthFlow.java
  airbyte-oauth/src/main/java/io/airbyte/oauth/flows/AmazonSellerPartnerOAuthFlow.java
Labels: area/connectors

#282 CU-866a1pmwr_When-canceling-adding-new-user-the-input-field-will-show-as-required_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/InviteUserModal.tsx
Labels: area/platform, team/frontend

#283 CU-860qc3zyt_Update-Amazon-SP-fields_igor_
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/source.py
  airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/spec.py
Labels: area/connectors

#284 CU-860qc3zyt_Update-Amazon-SP-fields_haimin-
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/source.py
  airbyte-integrations/connectors/source-amazon-seller-partner/source_amazon_seller_partner/spec.py
Labels: area/connectors

#285 CU-860qc3zyt_Update-Amazon-SP-fields_igor_
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  docs/integrations/sources/amazon-seller-partner.md
  docs/setup-guide/sources/amazon-seller-partner.md
  docs/zh/setup-guide/sources/amazon-seller-partner.md
Labels: area/documentation

#286 CU-860qc3zyt_Update-Amazon-SP-fields_haimin-
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  docs/integrations/sources/amazon-seller-partner.md
  docs/setup-guide/sources/amazon-seller-partner.md
  docs/zh/setup-guide/sources/amazon-seller-partner.md
Labels: area/documentation

#288 CU-865c63n6y_Amazon-SP_haimin-
  airbyte-oauth/src/main/java/io/airbyte/oauth/flows/AmazonSellerPartnerOAuthFlow.java
  airbyte-webapp/README.md
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/InviteUserModal.tsx
Labels: area/platform, team/frontend
