Repository Yuanrui-Mdt-Info/airbyte, pull requests merged in 2023-12, with the labels that each got.

#457 CU-866b25kha_---DA20231010-044---Billing-related-issues_Nick
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/views/layout/Banners/UpgradePlanBanner/UpgradePlanBanner.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend

#458 CU-866b0r9tt_---DA20231012-066---Performance-issue-on-production---further-optimizations_Shoaib-Ejaz
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
Labels: area/platform, team/frontend

#461 CU-866b13we1_---DA20231110-076---Filters-on-sources--destinations-page_Nick
  airbyte-api/src/main/openapi/config.yaml
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/utils/common.ts
  airbyte-webapp/src/views/layout/Banners/UpgradePlanBanner/UpgradePlanBanner.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/platform, team/frontend, area/api, area/server

#462 Yuanrui dev
  airbyte-api/src/main/openapi/config.yaml
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-feishu/source_feishu/common.py
  airbyte-integrations/connectors/source-feishu/source_feishu/constraints.py
  airbyte-integrations/connectors/source-feishu/source_feishu/source.py
  airbyte-integrations/connectors/source-feishu/source_feishu/streams.py
  airbyte-integrations/connectors/source-shein/Dockerfile
  airbyte-integrations/connectors/source-shein/source_shein/source.py
  airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendConnectionsHandler.java
  airbyte-webapp/src/components/ConnectionStep/components/StepBox.tsx
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/NewItemTable.tsx
  airbyte-webapp/src/components/EntityTable/types.ts
  airbyte-webapp/src/core/request/AirbyteClient.ts
  airbyte-webapp/src/core/request/AirbyteClient1.ts
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/components/NewDestinationConnectionTable.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/UserTable.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/components/NewSourceConnectionTable.tsx
  airbyte-webapp/src/utils/common.ts
  airbyte-webapp/src/views/layout/Banners/UpgradePlanBanner/UpgradePlanBanner.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
Labels: area/connectors, area/platform, team/frontend, area/api, area/server

#463 CU-866b0r9nb_---DA20231012-066---Performance-issue-on-production---further-optimizations_Nick
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
Labels: area/platform, area/server

#465 CU-866b13wd8_---DA20231110-076---Filters-on-sources--destinations-page_Shoaib-Ejaz
  airbyte-webapp/src/core/request/AirbyteClient1.ts
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
Labels: area/platform, team/frontend

#467 CU-866b2k9j8_---DA20231012-066---Performance-issue-on-production_Shoaib-Ejaz
  airbyte-webapp/.env
  airbyte-webapp/src/components/JobItem/JobItem.tsx
  airbyte-webapp/src/components/JobItem/components/MainInfo.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/NewConnectionsTable.tsx
Labels: area/platform, team/frontend

#468 CU-866b2k9j8_---DA20231012-066---Performance-issue-on-production_haimin-
  airbyte-webapp/.env
  airbyte-webapp/src/components/JobItem/JobItem.tsx
  airbyte-webapp/src/components/JobItem/components/MainInfo.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/NewConnectionsTable.tsx
Labels: area/platform, team/frontend

#469 CU-866b2kfn1_---DA20231029-069---UI-improvements_Shoaib-Ejaz
  airbyte-webapp/src/components/JobItem/components/MainInfo.tsx
  airbyte-webapp/src/components/Pagination/Icons/EndIcon.tsx
  airbyte-webapp/src/components/Pagination/Icons/NextIcon.tsx
  airbyte-webapp/src/components/Pagination/Icons/PrevIcon.tsx
  airbyte-webapp/src/components/Pagination/Icons/StartIcon.tsx
  airbyte-webapp/src/components/Pagination/Pagination.tsx
  airbyte-webapp/src/components/base/DropDown/DropDown.tsx
  airbyte-webapp/src/components/icons/NewTabSecondIcon.tsx
  airbyte-webapp/src/components/icons/QuestionIcon.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/SelectConnectionPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/TestConnection.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/UserTable.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#472 CU-866b2u2tb_---DAPB20231207-017---Unable-to-select-a-particular-plan_Shoaib-Ejaz
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/ProfessionalCell.tsx
Labels: area/platform, team/frontend

#474 Yuanrui dev
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/SelectConnectionPage.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/ProfessionalCell.tsx
  airbyte-webapp/src/views/Connector/TestConnection/components/FooterButtons.tsx
Labels: area/platform, team/frontend

#478 CU-866b2u24k_---DAPB20231207-015---Manual-schedule-not-display-correctly_Nick
  airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
  airbyte-workers/src/main/java/io/airbyte/workers/process/KubePodProcess.java
Labels: area/platform, team/frontend, area/worker

#479 CU-866b2u24k_---DAPB20231207-015---Manual-schedule-not-display-correctly_haimin-
  airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
  airbyte-workers/src/main/java/io/airbyte/workers/process/KubePodProcess.java
  docs/setup-guide/sources/zendesk-support.md
  kube/overlays/dev-integration-test/.env
  kube/overlays/staging/.env
Labels: area/platform, team/frontend, area/worker, area/documentation

#480 CU-866b2wrg7_---DA20231110-076---Filters-on-sources--destinations-page_Nick
  airbyte-api/src/main/openapi/config.yaml
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendConnectionsHandler.java
  airbyte-webapp/src/core/domain/connection/WebBackendConnectionService.ts
  airbyte-webapp/src/core/request/AirbyteClient.ts
  airbyte-webapp/src/core/request/AirbyteClient1.ts
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
  docs/reference/api/generated-api-html/index.html
Labels: area/platform, team/frontend, area/api, area/server, area/documentation

#482 CU-860q6npqu_Remove-Store-name-field-in-Amazon-ads-and-make-it-not-mandatory_Nick
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/common.py
Labels: area/connectors

#481 CU-866b2wrg7_---DA20231110-076---Filters-on-sources--destinations-page_Xuan-Ma
  airbyte-api/src/main/openapi/config.yaml
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-integrations/connectors/source-amazon-ads/source_amazon_ads/streams/common.py
  airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendConnectionsHandler.java
  airbyte-webapp/src/core/domain/connection/WebBackendConnectionService.ts
  airbyte-webapp/src/core/request/AirbyteClient.ts
  airbyte-webapp/src/core/request/AirbyteClient1.ts
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
  docs/reference/api/generated-api-html/index.html
Labels: area/connectors, area/platform, team/frontend, area/api, area/server, area/documentation

#487 CU-860t4zra3_---DA20231110-076---Add-sourcedestination-redirect_Shoaib-Ejaz
  airbyte-webapp/src/hooks/services/useDestinationHook.tsx
  airbyte-webapp/src/hooks/services/useSourceHook.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/CreateDestinationPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/CreateSourcePage.tsx
Labels: area/platform, team/frontend

#488 CU-860t4zra3_---DA20231110-076---Add-sourcedestination-redirect_Mary
  airbyte-webapp/src/hooks/services/useDestinationHook.tsx
  airbyte-webapp/src/hooks/services/useSourceHook.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/CreateDestinationPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/CreateSourcePage.tsx
Labels: area/platform, team/frontend

#490 CU-860t4uyqq_---DAPB20231219-018---Netsuite-field-wrongly-highlighted_Shoaib-Ejaz
  airbyte-webapp/src/core/jsonSchema/schemaToYup.ts
Labels: area/platform, team/frontend

#491 CU-860t55np2_---DAPB20231222-019---Remove-back-button-in-source-and-destination-testing-page_Shoaib-Ejaz
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/TestConnection.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/CreateDestinationPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/CreateSourcePage.tsx
  airbyte-webapp/src/views/Connector/TestConnection/TestConnection.tsx
  airbyte-webapp/src/views/Connector/TestConnection/components/FooterButtons.tsx
Labels: area/platform, team/frontend

#495 CU-860t50mkv_---DA20231220-103---Integration-settings-optimization_Shoaib-Ejaz
  airbyte-webapp/package-lock.json
  airbyte-webapp/package.json
  airbyte-webapp/src/components/DatePicker/DatePicker.module.scss
  airbyte-webapp/src/components/DatePicker/DatePicker.test.tsx
  airbyte-webapp/src/components/DatePicker/DatePicker.tsx
  airbyte-webapp/src/components/DatePicker/index.tsx
  airbyte-webapp/src/components/NewButton/NewButton.module.scss
  airbyte-webapp/src/components/NewButton/NewButton.tsx
  airbyte-webapp/src/components/NewButton/index.tsx
  airbyte-webapp/src/components/NewButton/types.tsx
  airbyte-webapp/src/components/base/Input/Input.tsx
  airbyte-webapp/src/core/jsonSchema/schemaToUiWidget.ts
  airbyte-webapp/src/core/jsonSchema/schemaToYup.ts
  airbyte-webapp/src/hooks/services/Experiment/experiments.ts
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/scss/_z-indices.scss
  airbyte-webapp/src/setupTests.ts
  airbyte-webapp/src/views/Connector/ServiceForm/components/Property/Control.tsx
Labels: area/platform, team/frontend

#494 CU-860t4f19c_---DA20231011-064---Webapp-responsiveness_Shoaib-Ejaz
  airbyte-webapp/src/views/Connector/TestConnection/components/FooterButtons.tsx
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#496 CU-86enc2rec_---DAPB20231222-019---Back-button-in-source-and-destination-testing-page_Mary
  airbyte-integrations/connectors/source-tiktok-marketing/Dockerfile
  airbyte-webapp/package-lock.json
  airbyte-webapp/package.json
  airbyte-webapp/src/components/DatePicker/DatePicker.module.scss
  airbyte-webapp/src/components/DatePicker/DatePicker.test.tsx
  airbyte-webapp/src/components/DatePicker/DatePicker.tsx
  airbyte-webapp/src/components/DatePicker/index.tsx
  airbyte-webapp/src/components/NewButton/NewButton.module.scss
  airbyte-webapp/src/components/NewButton/NewButton.tsx
  airbyte-webapp/src/components/NewButton/index.tsx
  airbyte-webapp/src/components/NewButton/types.tsx
  airbyte-webapp/src/components/base/Input/Input.tsx
  airbyte-webapp/src/core/jsonSchema/schemaToUiWidget.ts
  airbyte-webapp/src/core/jsonSchema/schemaToYup.ts
  airbyte-webapp/src/hooks/services/Experiment/experiments.ts
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/scss/_z-indices.scss
  airbyte-webapp/src/setupTests.ts
  airbyte-webapp/src/views/Connector/ServiceForm/components/Property/Control.tsx
  airbyte-webapp/src/views/Connector/TestConnection/components/FooterButtons.tsx
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/connectors, area/platform, team/frontend

#499 CU-860t4m566_---DA20231010-047---Abilitytosortconnectionssourcesdestinations_Nick
  airbyte-api/src/main/openapi/config.yaml
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/ConnectionsHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
Labels: area/platform, area/api, area/server

#500 CU-860t55np2_---DAPB20231222-019---Remove-back-button-in-source-and-destination-testing-page_Shoaib-Ejaz
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/TestConnection.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/CreateControls.tsx
Labels: area/platform, team/frontend

#502 CU-860t4m566_---DA20231010-047---Abilitytosortconnectionssourcesdestinations_Nick
  airbyte-api/src/main/openapi/config.yaml
  airbyte-server/src/main/java/io/airbyte/server/handlers/ConnectionsHandler.java
Labels: area/platform, area/api, area/server

#504 CU-860t4mrfw_---DA20231010-047---Abilitytosortconnectionssourcesdestinations_Shoaib-Ejaz
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/DestinationTable.tsx
  airbyte-webapp/src/components/EntityTable/SourceTable.tsx
  airbyte-webapp/src/components/EntityTable/components/SortButton.tsx
  airbyte-webapp/src/components/icons/ArrowDownIcon.tsx
  airbyte-webapp/src/components/icons/ArrowUpIcon.tsx
  airbyte-webapp/src/components/icons/SortDownIcon.tsx
  airbyte-webapp/src/components/icons/SortUpIcon.tsx
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/NewConnectionsTable.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/components/DestinationsTable.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/components/SourcesTable.tsx
Labels: area/platform, team/frontend

#505 CU-86enc2rec_---DAPB20231222-019---Back-button-in-source-and-destination-testing-page_Mary
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/DestinationTable.tsx
  airbyte-webapp/src/components/EntityTable/SourceTable.tsx
  airbyte-webapp/src/components/EntityTable/components/SortButton.tsx
  airbyte-webapp/src/components/icons/ArrowDownIcon.tsx
  airbyte-webapp/src/components/icons/ArrowUpIcon.tsx
  airbyte-webapp/src/components/icons/SortDownIcon.tsx
  airbyte-webapp/src/components/icons/SortUpIcon.tsx
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/NewConnectionsTable.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/components/DestinationsTable.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/components/SourcesTable.tsx
Labels: area/platform, team/frontend

#506 CU-860t4mrfw_---DA20231010-047---Abilitytosortconnectionssourcesdestinations_Shoaib-Ejaz
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/DestinationTable.tsx
  airbyte-webapp/src/components/EntityTable/SourceTable.tsx
  airbyte-webapp/src/core/request/AirbyteClient.ts
  airbyte-webapp/src/core/request/AirbyteClient1.ts
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/components/NewConnectionsTable.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/components/DestinationsTable.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/components/SourcesTable.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
Labels: area/platform, team/frontend
