Repository Yuanrui-Mdt-Info/airbyte, pull requests merged in 2023-10, with the labels that each got.

#380 CU 85zu1bxnn - Change the app installation popup in browser
  airbyte-webapp/public/manifest.json
Labels: area/platform, team/frontend

#381 CU-85zu2fb9z_Check-the-issue-that-predaspirecom-doesnt-show-destinations-and-sources_Shoaib-Ejaz
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/components/DestinationsTable.tsx
Labels: area/platform, team/frontend

#385 CU-85zu0d6f2_Notify-the-user-free-trial-has-expired-when-they-try-to-save-a-connection_Shoaib-Ejaz
  airbyte-webapp/src/components/Alert/Alert.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ReplicationView.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
Labels: area/platform, team/frontend

#384 CU-85zu2163v_QA-Change-the-app-installation-popup-in-browser_Shoaib-Ejaz
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
Labels: area/platform, team/frontend

#383 CU-85zu2fb9z_Check-the-issue-that-predaspirecom-doesnt-show-destinations-and-sources_Shoaib-Ejaz
  airbyte-webapp/.env
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/components/DestinationsTable.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/components/SourcesTable.tsx
Labels: area/platform, team/frontend

#382 CU-866art77q_Walmart-sync-failure_Nick
  airbyte-config/init/src/main/resources/seed/source_definitions.yaml
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-walmart/Dockerfile
Labels: area/connectors

#386 CU-85zu0e0vv_It-takes-a-while-for-the-change-made-to-appear_Shoaib-Ejaz
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/ConnectionItemPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ReplicationView.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/formConfig.tsx
Labels: area/platform, team/frontend

#387 CU-85zu0e0vv_It-takes-a-while-for-the-change-made-to-appear_Abi---
  airbyte-webapp/src/components/Alert/Alert.tsx
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/ConnectionItemPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ReplicationView.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/AccountSettingsPage/components/Sidebar.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/formConfig.tsx
Labels: area/platform, team/frontend

#388 Ability to connect to Walmart CA
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-walmart/Dockerfile
  airbyte-integrations/connectors/source-walmart/requirements.txt
  airbyte-integrations/connectors/source-walmart/source_walmart/source.py
  airbyte-integrations/connectors/source-walmart/source_walmart/spec.yaml
Labels: area/connectors

#390 CU-85zu3udwz_BE-address-performance-issue-on-production_Nick
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-config/init/src/main/resources/seed/source_definitions.yaml
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-walmart/Dockerfile
  airbyte-server/src/main/java/io/airbyte/server/handlers/ConnectionsHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendConnectionsHandler.java
Labels: area/connectors, area/platform, area/server

#391 CU-85zu3udwz_BE-address-performance-issue-on-production_Nick
  airbyte-server/src/main/java/io/airbyte/server/handlers/ConnectionsHandler.java
Labels: area/platform, area/server

#392 CU-866atd7tv_BE-pagination-on-sourcedestination-pages_Nick
  airbyte-api/src/main/openapi/config.yaml
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/DbConverter.java
  airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
Labels: area/platform, area/api, area/server

#393 CU-866ayxydt_---DAPB20231013-011---performanceissueontheproductionenv_Shoaib-Ejaz
  airbyte-webapp/src/components/EntityTable/DestinationTable.tsx
  airbyte-webapp/src/components/EntityTable/ImplementationTable.tsx
  airbyte-webapp/src/components/EntityTable/SourceTable.tsx
  airbyte-webapp/src/components/EntityTable/types.ts
  airbyte-webapp/src/core/domain/connector/SourceService.ts
  airbyte-webapp/src/core/request/AirbyteClient.ts
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/hooks/services/useSourceHook.tsx
  airbyte-webapp/src/pages/AuthPage/LoginNewPage/LoginNewPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/components/DestinationsTable.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/components/SourcesTable.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
Labels: area/platform, team/frontend

#394 CU-866az8f2f_---DA20230924-001---Ability-to-connect-to-Walmart-CA_Abi---
  airbyte-api/src/main/openapi/config.yaml
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/DbConverter.java
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-walmart/Dockerfile
  airbyte-integrations/connectors/source-walmart/requirements.txt
  airbyte-integrations/connectors/source-walmart/source_walmart/source.py
  airbyte-integrations/connectors/source-walmart/source_walmart/spec.yaml
  airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/ConnectionsHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendConnectionsHandler.java
Labels: area/connectors, area/platform, area/api, area/server

#398 CU-866az8ctg_---DA20231012-066---Performance-issue-on-production---create-a-new-API-that-contains-source-and-source-specific-connection-data-for-this_Nick
  airbyte-api/src/main/openapi/config.yaml
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/ConnectionsHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendConnectionsHandler.java
Labels: area/platform, area/api, area/server

#399 resolved some performance issue
  airbyte-api/src/main/openapi/config.yaml
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/ConnectionsHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendConnectionsHandler.java
Labels: area/platform, area/api, area/server

#400 CU-866az89hv_---DAPB20231013-012---peformanceissueonopeningasinglesourceordestination_Shoaib-Ejaz
  airbyte-integrations/connectors/source-currencylayer/setup.py
  airbyte-integrations/connectors/source-newegg/setup.py
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/DestinationTable.tsx
  airbyte-webapp/src/components/EntityTable/ImplementationTable.tsx
  airbyte-webapp/src/components/EntityTable/SourceTable.tsx
  airbyte-webapp/src/components/EntityTable/types.ts
  airbyte-webapp/src/core/domain/connector/DestinationService.ts
  airbyte-webapp/src/core/domain/connector/SourceService.ts
  airbyte-webapp/src/core/request/AirbyteClient.ts
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/hooks/services/useDestinationHook.tsx
  airbyte-webapp/src/hooks/services/useSourceHook.tsx
  airbyte-webapp/src/pages/AuthPage/LoginNewPage/LoginNewPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/components/DestinationsTable.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/components/SourcesTable.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/components/HeaderSection.tsx
Labels: area/connectors, area/platform, team/frontend

#401 CU-866az8jdf_---DA20231005-017---Pagination-on-sourcedestination-pages_haimin-
  airbyte-integrations/connectors/source-currencylayer/setup.py
  airbyte-integrations/connectors/source-newegg/setup.py
  airbyte-webapp/src/components/EntityTable/ConnectionTable.tsx
  airbyte-webapp/src/components/EntityTable/DestinationTable.tsx
  airbyte-webapp/src/components/EntityTable/ImplementationTable.tsx
  airbyte-webapp/src/components/EntityTable/SourceTable.tsx
  airbyte-webapp/src/components/EntityTable/types.ts
  airbyte-webapp/src/core/domain/connector/DestinationService.ts
  airbyte-webapp/src/core/domain/connector/SourceService.ts
  airbyte-webapp/src/core/request/AirbyteClient.ts
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/hooks/services/useDestinationHook.tsx
  airbyte-webapp/src/hooks/services/useSourceHook.tsx
  airbyte-webapp/src/pages/AuthPage/LoginNewPage/LoginNewPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/components/DestinationsTable.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/components/SourcesTable.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/components/HeaderSection.tsx
Labels: area/connectors, area/platform, team/frontend

#404 CU-867917bp6_UI-improvements_Shoaib-Ejaz
  airbyte-webapp/src/components/EntityTable/DestinationTable.tsx
  airbyte-webapp/src/components/EntityTable/SourceTable.tsx
  airbyte-webapp/src/components/PageSize/PageSize.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/CreateDestinationPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/CreateSourcePage.tsx
  airbyte-webapp/src/views/Connector/TestConnection/TestConnection.tsx
  airbyte-webapp/src/views/Connector/TestConnection/components/TestingLoading.tsx
  airbyte-webapp/src/views/Connector/TestConnection/components/TestingSuccess.tsx
Labels: area/platform, team/frontend

#406 CU-85zu4abdw_Webapp-responsiveness_Shoaib-Ejaz
  airbyte-webapp/src/components/ConnectorCard/ConnectorCard.tsx
  airbyte-webapp/src/components/JobItem/components/AttemptDetails.module.scss
  airbyte-webapp/src/components/JobItem/components/MainInfo.module.scss
  airbyte-webapp/src/components/JobItem/components/MainInfo.tsx
  airbyte-webapp/src/components/SimpleTableComponents/SimpleTableComponents.tsx
  airbyte-webapp/src/components/base/Button/BigButton.tsx
  airbyte-webapp/src/core/request/AirbyteClient1.ts
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ConnectionName.module.scss
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/ConnectionName.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusMainInfo.module.scss
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.module.scss
  airbyte-webapp/src/pages/ConnectionPage/pages/ConnectionItemPage/components/StatusView.tsx
  airbyte-webapp/src/views/Connection/CatalogTree/StreamHeader.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/ConnectionForm.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/SyncCatalogField.module.scss
Labels: area/platform, team/frontend

#407 CU-866b0a0zu_---DA20231029-069---UI-improvements_Shoaib-Ejaz
  airbyte-webapp/src/components/Pagination/Pagination.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/AllDestinationsPage/AllDestinationsPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/AllSourcesPage/AllSourcesPage.tsx
Labels: area/platform, team/frontend

#409 CU-867917bp6_UI-improvements_Shoaib-Ejaz
  airbyte-webapp/src/components/base/Button/BigButton.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CopyDestinationPage/CopyDestinationPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CopySourcePage/CopySourcePage.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/CreateControls.tsx
  airbyte-webapp/src/views/Connection/ConnectionForm/components/EditControls.tsx
Labels: area/platform, team/frontend
