Repository Yuanrui-Mdt-Info/airbyte, pull requests merged in 2023-01, with the labels that each got.

#100 CU-860pdx7kn_Role-management_Muhammad-Akif
  airbyte-webapp/src/config/defaultConfig.ts
  airbyte-webapp/src/config/types.ts
  airbyte-webapp/src/core/ApiServices.tsx
  airbyte-webapp/src/core/AuthContext/AuthContext.tsx
  airbyte-webapp/src/hooks/services/UserDetail/UserDetailPoll.tsx
  airbyte-webapp/src/hooks/services/UserDetail/index.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/routes.tsx
Labels: area/platform, team/frontend

#102 CU-865bed37b__Roy--
  airbyte-workers/src/main/java/io/airbyte/workers/normalization/NormalizationRunnerFactory.java
Labels: area/platform, area/worker

#105 CU-860pd0f09_FE-pagination-UI_Muhammad-Akif
  airbyte-webapp/.env
  airbyte-webapp/src/components/Pagination/Icons/EndIcon.tsx
  airbyte-webapp/src/components/Pagination/Icons/NextIcon.tsx
  airbyte-webapp/src/components/Pagination/Icons/PrevIcon.tsx
  airbyte-webapp/src/components/Pagination/Icons/StartIcon.tsx
  airbyte-webapp/src/components/Pagination/Icons/index.tsx
  airbyte-webapp/src/components/Pagination/Pagination.tsx
  airbyte-webapp/src/components/Pagination/index.tsx
  airbyte-webapp/src/components/base/DropDown/CustomSelect.tsx
  airbyte-webapp/src/components/base/DropDown/DropDown.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/UserRoleDropdown.tsx
Labels: area/platform, team/frontend

#106 CU-37bznxn_QA-3-roles-with-different-accesses_Abi---
  airbyte-api/src/main/openapi/config.yaml
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-server/src/main/java/io/airbyte/server/apis/ConfigurationApi.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/ConnectionsHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/DestinationHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/SourceHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/WebBackendConnectionsHandler.java
  airbyte-webapp/.env
  airbyte-webapp/orval.config.ts
  airbyte-webapp/src/components/Pagination/Icons/EndIcon.tsx
  airbyte-webapp/src/components/Pagination/Icons/NextIcon.tsx
  airbyte-webapp/src/components/Pagination/Icons/PrevIcon.tsx
  airbyte-webapp/src/components/Pagination/Icons/StartIcon.tsx
  airbyte-webapp/src/components/Pagination/Icons/index.tsx
  airbyte-webapp/src/components/Pagination/Pagination.tsx
  airbyte-webapp/src/components/Pagination/index.tsx
  airbyte-webapp/src/components/base/DropDown/CustomSelect.tsx
  airbyte-webapp/src/components/base/DropDown/DropDown.tsx
  airbyte-webapp/src/components/icons/DeleteIcon.tsx
  airbyte-webapp/src/components/icons/RefreshIcon.tsx
  airbyte-webapp/src/config/defaultConfig.ts
  airbyte-webapp/src/config/types.ts
  airbyte-webapp/src/core/ApiServices.tsx
  airbyte-webapp/src/core/AuthContext/AuthContext.tsx
  airbyte-webapp/src/core/domain/role/Role.tsx
  airbyte-webapp/src/core/domain/role/RoleService.tsx
  airbyte-webapp/src/core/domain/role/index.tsx
  airbyte-webapp/src/core/domain/user/User.tsx
  airbyte-webapp/src/core/domain/user/UserService.tsx
  airbyte-webapp/src/core/domain/user/index.tsx
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/hooks/services/UserDetail/UserDetailPoll.tsx
  airbyte-webapp/src/hooks/services/UserDetail/index.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/AuthPage/UserSignupPage/UserSignupPage.tsx
  airbyte-webapp/src/pages/AuthPage/UserSignupPage/components/SignupForm.module.scss
  airbyte-webapp/src/pages/AuthPage/UserSignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/AuthPage/UserSignupPage/index.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/components/MessageBox.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/ChangeRoleModal.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/DeleteUserModal.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/InviteUserModal.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/UserRoleDropdown.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/UserTable.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/UserTableBody.tsx
  airbyte-webapp/src/pages/routePaths.tsx
  airbyte-webapp/src/pages/routes.tsx
  airbyte-webapp/src/services/roles/RolesService.tsx
  airbyte-webapp/src/services/users/UsersService.tsx
  airbyte-webapp/src/views/layout/MainView/MainView.tsx
  airbyte-workers/src/main/java/io/airbyte/workers/temporal/scheduling/activities/JobCreationAndStatusUpdateActivityImpl.java
Labels: area/platform, team/frontend, area/api, area/server, area/worker

#107 CU-860pgnbq6_Add-users-name-and-email-on-sidebar_Muhammad-Akif
  airbyte-webapp/.env
  airbyte-webapp/src/core/request/AirbyteClient1.ts
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#108 CU-860pgnbq6_Add-users-name-and-email-on-sidebar_Abi---
  airbyte-webapp/.env
  airbyte-webapp/src/core/request/AirbyteClient1.ts
  airbyte-webapp/src/views/layout/SideBar/SideBar.tsx
Labels: area/platform, team/frontend

#109 CU-865bfgnbe_bugNo-prompt-when-inviting-an-existing-email-accountand-it-is-always-loading_Muhammad-Akif
  airbyte-webapp/src/core/request/apiOverride.ts
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/components/MessageBox.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/InviteUserModal.tsx
Labels: area/platform, team/frontend

#110 CU-860pe8p6c_FE-Sign-up-sign-in-with-Google_Muhammad-Akif
  airbyte-webapp/package-lock.json
  airbyte-webapp/package.json
  airbyte-webapp/src/App.tsx
  airbyte-webapp/src/components/icons/GoogleIcon.tsx
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/AuthPage/GoogleAuthBtn/GoogleAuthBtn.tsx
  airbyte-webapp/src/pages/AuthPage/GoogleAuthBtn/index.tsx
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/services/auth/AuthService.ts
Labels: area/platform, team/frontend

#111 CU-86698hy91_Change-link-in-connection-config_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/config/links.ts
Labels: area/platform, team/frontend

#113 CU-860pe7vb3_New-source-Walmart_Roy--
  airbyte-integrations/connectors/source-walmart/.dockerignore
  airbyte-integrations/connectors/source-walmart/Dockerfile
  airbyte-integrations/connectors/source-walmart/README.md
  airbyte-integrations/connectors/source-walmart/acceptance-test-config.yml
  airbyte-integrations/connectors/source-walmart/acceptance-test-docker.sh
  airbyte-integrations/connectors/source-walmart/build.gradle
  airbyte-integrations/connectors/source-walmart/integration_tests/__init__.py
  airbyte-integrations/connectors/source-walmart/integration_tests/abnormal_state.json
  airbyte-integrations/connectors/source-walmart/integration_tests/acceptance.py
  airbyte-integrations/connectors/source-walmart/integration_tests/catalog.json
  airbyte-integrations/connectors/source-walmart/integration_tests/configured_catalog.json
  airbyte-integrations/connectors/source-walmart/integration_tests/invalid_config.json
  airbyte-integrations/connectors/source-walmart/integration_tests/sample_config.json
  airbyte-integrations/connectors/source-walmart/integration_tests/sample_state.json
  airbyte-integrations/connectors/source-walmart/main.py
  airbyte-integrations/connectors/source-walmart/requirements.txt
  airbyte-integrations/connectors/source-walmart/setup.py
  airbyte-integrations/connectors/source-walmart/source_walmart/__init__.py
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/DEPARTMENTS.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/GET_SHIPMENTS.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/GET_SHIPMENT_ITEMS.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/INVENTORY_MULTIPLE_ITEM.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/INVENTORY_WFS.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/ITEMS.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/ORDERS_3PL_FULFILLED.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/ORDERS_SELLER_FULFILLED.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/ORDERS_WFS_FULFILLED.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/REQUESTS_BUYBOX.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/REQUESTS_CPA.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/REQUESTS_ITEM.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/REQUESTS_ITEM_PERFORMANCE.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/REQUESTS_PROMO.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/REQUESTS_RETURN_OVERRIDES.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/REQUESTS_SHIPPING_CONFIGURATION.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/REQUESTS_SHIPPING_PROGRAM.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/RETURNS.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/TODO.md
  airbyte-integrations/connectors/source-walmart/source_walmart/source.py
  airbyte-integrations/connectors/source-walmart/source_walmart/spec.yaml
  airbyte-integrations/connectors/source-walmart/unit_tests/__init__.py
  airbyte-integrations/connectors/source-walmart/unit_tests/test_incremental_streams.py
  airbyte-integrations/connectors/source-walmart/unit_tests/test_source.py
  airbyte-integrations/connectors/source-walmart/unit_tests/test_streams.py
Labels: area/connectors

#112 CU-86698hxbe_Hide-sync-log_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/components/JobItem/JobItem.tsx
Labels: area/platform, team/frontend

#114 CU-86698hxbe_Hide-sync-log_Abi---
  airbyte-integrations/connectors/source-walmart/.dockerignore
  airbyte-integrations/connectors/source-walmart/Dockerfile
  airbyte-integrations/connectors/source-walmart/README.md
  airbyte-integrations/connectors/source-walmart/acceptance-test-config.yml
  airbyte-integrations/connectors/source-walmart/acceptance-test-docker.sh
  airbyte-integrations/connectors/source-walmart/build.gradle
  airbyte-integrations/connectors/source-walmart/integration_tests/__init__.py
  airbyte-integrations/connectors/source-walmart/integration_tests/abnormal_state.json
  airbyte-integrations/connectors/source-walmart/integration_tests/acceptance.py
  airbyte-integrations/connectors/source-walmart/integration_tests/catalog.json
  airbyte-integrations/connectors/source-walmart/integration_tests/configured_catalog.json
  airbyte-integrations/connectors/source-walmart/integration_tests/invalid_config.json
  airbyte-integrations/connectors/source-walmart/integration_tests/sample_config.json
  airbyte-integrations/connectors/source-walmart/integration_tests/sample_state.json
  airbyte-integrations/connectors/source-walmart/main.py
  airbyte-integrations/connectors/source-walmart/requirements.txt
  airbyte-integrations/connectors/source-walmart/setup.py
  airbyte-integrations/connectors/source-walmart/source_walmart/__init__.py
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/DEPARTMENTS.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/GET_SHIPMENTS.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/GET_SHIPMENT_ITEMS.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/INVENTORY_MULTIPLE_ITEM.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/INVENTORY_WFS.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/ITEMS.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/ORDERS_3PL_FULFILLED.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/ORDERS_SELLER_FULFILLED.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/ORDERS_WFS_FULFILLED.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/REQUESTS_BUYBOX.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/REQUESTS_CPA.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/REQUESTS_ITEM.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/REQUESTS_ITEM_PERFORMANCE.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/REQUESTS_PROMO.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/REQUESTS_RETURN_OVERRIDES.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/REQUESTS_SHIPPING_CONFIGURATION.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/REQUESTS_SHIPPING_PROGRAM.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/RETURNS.json
  airbyte-integrations/connectors/source-walmart/source_walmart/schemas/TODO.md
  airbyte-integrations/connectors/source-walmart/source_walmart/source.py
  airbyte-integrations/connectors/source-walmart/source_walmart/spec.yaml
  airbyte-integrations/connectors/source-walmart/unit_tests/__init__.py
  airbyte-integrations/connectors/source-walmart/unit_tests/test_incremental_streams.py
  airbyte-integrations/connectors/source-walmart/unit_tests/test_source.py
  airbyte-integrations/connectors/source-walmart/unit_tests/test_streams.py
  airbyte-webapp/README.md
  airbyte-webapp/package-lock.json
  airbyte-webapp/package.json
  airbyte-webapp/src/App.tsx
  airbyte-webapp/src/components/JobItem/JobItem.tsx
  airbyte-webapp/src/components/icons/GoogleIcon.tsx
  airbyte-webapp/src/config/links.ts
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/AuthPage/GoogleAuthBtn/GoogleAuthBtn.tsx
  airbyte-webapp/src/pages/AuthPage/GoogleAuthBtn/index.tsx
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/AllConnectionsPage/AllConnectionsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/services/auth/AuthService.ts
Labels: area/connectors, area/platform, team/frontend

#116 CU-860pe7vb3_New-source-Walmart_Roy--
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-walmart/source_walmart/spec.yaml
Labels: area/connectors

#117 CU-860pe8p6c_FE-Sign-up-sign-in-with-Google_haimin-
  airbyte-config/init/src/main/resources/icons/walmart.svg
  airbyte-config/init/src/main/resources/seed/source_definitions.yaml
  airbyte-config/init/src/main/resources/seed/source_specs.yaml
  airbyte-integrations/connectors/source-walmart/source_walmart/spec.yaml
Labels: area/connectors

#118 CU-860pme70e_Bug-sign-up-page-UI-issue_Muhammad-Akif
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/AuthPage/GoogleAuthBtn/GoogleAuthBtn.tsx
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.module.scss
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/PaymentErrorPage/PaymentErrorPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
Labels: area/platform, team/frontend

#119 CU-860pg6j6j_Back-from-the-payment-page-should-redirect-user_haimin-
  airbyte-webapp/src/core/request/apiOverride.ts
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/pages/AuthPage/GoogleAuthBtn/GoogleAuthBtn.tsx
  airbyte-webapp/src/pages/AuthPage/LoginPage/LoginPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.module.scss
  airbyte-webapp/src/pages/AuthPage/SignupPage/components/SignupForm.tsx
  airbyte-webapp/src/pages/PaymentErrorPage/PaymentErrorPage.tsx
  airbyte-webapp/src/pages/SettingsPage/SettingsPage.tsx
  airbyte-webapp/src/pages/SettingsPage/components/MessageBox.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/UserManagementPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/UserManagementPage/components/InviteUserModal.tsx
Labels: area/platform, team/frontend

#120 CU-860pk0t80_FE-change-wording-in-Alpha-connectors_Anet-
  airbyte-webapp/README.md
  airbyte-webapp/src/config/links.ts
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/views/Connector/ServiceForm/components/WarningMessage.tsx
Labels: area/platform, team/frontend

#121 CU-860pme6my_Bug-not-able-to-sign-up-sign-in-with-Google_Muhammad-Akif
  airbyte-webapp/src/pages/AuthPage/SignupPage/SignupPage.tsx
Labels: area/platform, team/frontend
