Repository Yuanrui-Mdt-Info/airbyte, pull requests merged in 2024-03, with the labels that each got.

#524 Yuanrui dev
  airbyte-api/src/main/openapi/config.yaml
  airbyte-config/config-models/src/main/java/io/airbyte/config/DaspireOauthHttpUtil.java
  airbyte-config/config-models/src/main/resources/types/StandardWorkspace.yaml
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ClassEnforcingConfigPersistence.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigPersistence.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/DatabaseConfigPersistence.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/DbConverter.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ValidatingConfigPersistence.java
  airbyte-config/config-persistence/src/test/java/io/airbyte/config/persistence/ConfigRepositoryE2EReadWriteTest.java
  airbyte-config/init/src/main/java/io/airbyte/config/init/DefinitionProviderToConfigPersistenceAdapter.java
  airbyte-config/init/src/main/java/io/airbyte/config/init/YamlSeedConfigPersistence.java
  airbyte-db/db-lib/src/main/java/io/airbyte/db/instance/configs/migrations/V0_40_3_003__AddTokenToWorkspace.java
  airbyte-db/db-lib/src/test/java/io/airbyte/db/instance/configs/migrations/V0_40_3_003__AddTokenToWorkspaceTest.java
  airbyte-integrations/bases/base-normalization/oracle.Dockerfile
  airbyte-integrations/bases/base-normalization/unit_tests/test_stream_processor.py
  airbyte-oauth/src/main/java/io/airbyte/oauth/BaseOAuthFlow.java
  airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/job_factory/OAuthConfigSupplier.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/OAuthHandler.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/WorkspacesHandler.java
  airbyte-server/src/test/java/io/airbyte/server/handlers/OAuthHandlerTest.java
  airbyte-webapp/.env
  airbyte-webapp/src/core/domain/payment/Payment.ts
  airbyte-webapp/src/core/domain/payment/PaymentService.tsx
  airbyte-webapp/src/core/domain/product/Product.ts
  airbyte-webapp/src/core/request/AirbyteClient1.ts
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/locales/en.json
  airbyte-webapp/src/locales/zh.json
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/BillingPaymentStep/BillingPaymentStep.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/SelectPlanStep.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/CloudProvider.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/DeploymentMode.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/FeatureNot.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/FeaturesCard.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/Instance.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/ProfessionalCell.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/Region.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/PlansBillingPage.tsx
  airbyte-webapp/src/pages/SettingsPage/pages/PlansBillingPage/style.module.scss
  airbyte-webapp/src/services/payments/PaymentsService.tsx
  docker-compose.yaml
  docs/reference/api/generated-api-html/index.html
  ingress-dev.yaml
  ingress-production.yaml
  ingress-staging.yaml
  kube/resources-dev/server.yaml
Labels: area/platform, team/frontend, area/api, area/server, area/scheduler, normalization, kubernetes, area/documentation

#533 Bug:Sync Status Show Incorrectly
  airbyte-webapp/src/components/JobItem/JobItem.tsx
  airbyte-webapp/src/components/JobItem/components/MainInfo.tsx
  airbyte-webapp/src/core/request/AirbyteClient.ts
Labels: area/platform, team/frontend

#536 Fixed the api url for free trial upgradation first time
  airbyte-webapp/src/core/domain/payment/PaymentService.tsx
  airbyte-webapp/src/core/request/DaspireClient.ts
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/FeaturesCard.tsx
  airbyte-webapp/src/services/payments/PaymentsService.tsx
Labels: area/platform, team/frontend

#535 add workspaceid in check_connection and discover_schema API request payload
  airbyte-api/src/main/openapi/config.yaml
  airbyte-server/src/main/java/io/airbyte/server/handlers/SchedulerHandler.java
Labels: area/platform, area/api, area/server

#538 Include workspaceid when making API calls
  airbyte-webapp/src/core/domain/connector/DestinationService.ts
  airbyte-webapp/src/core/domain/connector/SourceService.ts
  airbyte-webapp/src/core/request/AirbyteClient.ts
  airbyte-webapp/src/hooks/services/useConnector.tsx
  airbyte-webapp/src/hooks/services/useDestinationHook.tsx
  airbyte-webapp/src/hooks/services/useSourceHook.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/CreationFormPage.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/DestinationForm.tsx
  airbyte-webapp/src/pages/ConnectionPage/pages/CreationFormPage/components/SourceForm.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CopyDestinationPage/CopyDestinationPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/CreateDestinationPage.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/CreateDestinationPage/components/DestinationForm.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/DestinationItemPage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CopySourcePage/CopySourcePage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/CreateSourcePage.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/SourceItemPage.tsx
  airbyte-webapp/src/views/Connector/ConnectorCard/useTestConnector.tsx
  airbyte-webapp/src/views/Connector/ServiceForm/types.ts
  airbyte-webapp/src/views/Connector/ServiceForm/useBuildForm.tsx
Labels: area/platform, team/frontend

#542 Unsubscribed Plan (Upgrade Plan Disabled Button Issue fixed)
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/SelectPlanStep.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/FeaturesCard.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/ProfessionalCell.tsx
Labels: area/platform, team/frontend

#541 read config from daspire
  airbyte-config/config-models/src/main/java/io/airbyte/config/DaspireOauthHttpUtil.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ClassEnforcingConfigPersistence.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigPersistence.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/DatabaseConfigPersistence.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ValidatingConfigPersistence.java
  airbyte-config/config-persistence/src/test/java/io/airbyte/config/persistence/ConfigRepositoryE2EReadWriteTest.java
  airbyte-config/init/src/main/java/io/airbyte/config/init/DefinitionProviderToConfigPersistenceAdapter.java
  airbyte-config/init/src/main/java/io/airbyte/config/init/YamlSeedConfigPersistence.java
  airbyte-config/init/src/main/resources/seed/destination_definitions.yaml
  airbyte-config/init/src/main/resources/seed/source_definitions.yaml
  airbyte-oauth/src/main/java/io/airbyte/oauth/BaseOAuthFlow.java
  airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/job_factory/OAuthConfigSupplier.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/OAuthHandler.java
  airbyte-server/src/test/java/io/airbyte/server/handlers/OAuthHandlerTest.java
Labels: area/platform, area/server, area/scheduler

#543 initialize default data for actor_oauth_parameter table
  airbyte-config/config-models/src/main/java/io/airbyte/config/DaspireOauthHttpUtil.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ClassEnforcingConfigPersistence.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigPersistence.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ConfigRepository.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/DatabaseConfigPersistence.java
  airbyte-config/config-persistence/src/main/java/io/airbyte/config/persistence/ValidatingConfigPersistence.java
  airbyte-config/config-persistence/src/test/java/io/airbyte/config/persistence/ConfigRepositoryE2EReadWriteTest.java
  airbyte-config/init/src/main/java/io/airbyte/config/init/DefinitionProviderToConfigPersistenceAdapter.java
  airbyte-config/init/src/main/java/io/airbyte/config/init/SeedType.java
  airbyte-config/init/src/main/java/io/airbyte/config/init/YamlSeedConfigPersistence.java
  airbyte-config/init/src/main/resources/seed/destination_definitions.yaml
  airbyte-config/init/src/main/resources/seed/destination_oauth.yaml
  airbyte-config/init/src/main/resources/seed/source_definitions.yaml
  airbyte-config/init/src/main/resources/seed/source_oauth.yaml
  airbyte-db/db-lib/src/main/java/io/airbyte/db/instance/configs/migrations/V0_40_3_004__RemoveConfigurationNotNullConstraintFromOauthParamsTable.java
  airbyte-db/db-lib/src/test/java/io/airbyte/db/instance/configs/migrations/V0_40_3_003__AddTokenToWorkspaceTest.java
  airbyte-oauth/src/main/java/io/airbyte/oauth/BaseOAuthFlow.java
  airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/job_factory/OAuthConfigSupplier.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/OAuthHandler.java
  airbyte-server/src/test/java/io/airbyte/server/handlers/OAuthHandlerTest.java
Labels: area/platform, area/server, area/scheduler

#544 On Changeing Chinese Languge Conccurent Job value Issue Fixed
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/FeaturesCard.tsx
Labels: area/platform, team/frontend

#545 modify api request body
  airbyte-api/src/main/openapi/config.yaml
  airbyte-config/config-models/src/main/java/io/airbyte/config/DaspireOauthHttpUtil.java
  airbyte-server/src/main/java/io/airbyte/server/handlers/SchedulerHandler.java
Labels: area/platform, area/api, area/server

#547 Yuanrui test
  airbyte-webapp/src/pages/PaymentPage/PaymentPage.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/SelectPlanStep.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/FeaturesCard.tsx
  airbyte-webapp/src/pages/PaymentPage/steps/SelectPlanStep/components/ProfessionalCell.tsx
Labels: area/platform, team/frontend

#548 Add worksapce Id
  airbyte-webapp/src/hooks/services/useDestinationHook.tsx
  airbyte-webapp/src/hooks/services/useSourceHook.tsx
Labels: area/platform, team/frontend

#552 Worksapce Additon
  airbyte-webapp/src/core/request/AirbyteClient1.ts
  airbyte-webapp/src/hooks/services/useConnectionHook.tsx
  airbyte-webapp/src/hooks/services/useDestinationHook.tsx
  airbyte-webapp/src/hooks/services/useSourceHook.tsx
  airbyte-webapp/src/pages/DestinationPage/pages/DestinationItemPage/components/DestinationSettings.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/CreateSourcePage/components/SourceForm.tsx
  airbyte-webapp/src/pages/SourcesPage/pages/SourceItemPage/components/SourceSettings.tsx
  airbyte-webapp/src/views/Connector/ServiceForm/types.ts
Labels: area/platform, team/frontend

#551 remove deprecated field for shopify source connector
  airbyte-integrations/connectors/source-shopify/source_shopify/schemas/abandoned_checkouts.json
  airbyte-integrations/connectors/source-shopify/source_shopify/schemas/orders.json
  airbyte-integrations/connectors/source-shopify/source_shopify/source.py
Labels: area/connectors
